// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TageTable(	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
  input         io_f1_req_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [39:0] io_f1_req_pc,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [63:0] io_f1_req_ghist,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_0_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_0_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_0_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_1_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_1_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_1_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_2_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_2_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_2_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_3_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_3_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_3_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [39:0] io_update_pc,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [63:0] io_update_hist,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_3	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
);

  wire [3:0]  update_u_wdata_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:160:27]
  wire [2:0]  update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:149:33]
  wire [3:0]  update_u_wdata_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:160:27]
  wire [2:0]  update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:149:33]
  wire [3:0]  update_u_wdata_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:160:27]
  wire [2:0]  update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:149:33]
  wire [3:0]  update_u_wdata_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:160:27]
  wire [2:0]  update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:149:33]
  wire [3:0]  tage_us_MPORT_1_data_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:8]
  wire [3:0]  tage_us_MPORT_1_data_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:8]
  wire [3:0]  tage_us_MPORT_1_data_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:8]
  wire [3:0]  tage_us_MPORT_1_data_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:8]
  wire [10:0] table_MPORT_data_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:124:8]
  wire [10:0] table_MPORT_data_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:124:8]
  wire [10:0] table_MPORT_data_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:124:8]
  wire [10:0] table_MPORT_data_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:124:8]
  wire [43:0] _table_R0_data;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27]
  wire [15:0] _tage_us_R0_data;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28]
  reg         doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28]
  reg  [6:0]  reset_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:73:26]
  wire [6:0]  s1_hashed_idx = {io_f1_req_pc[9:5], io_f1_req_pc[4:3] ^ io_f1_req_ghist[1:0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :60:{29,43}, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
  reg  [6:0]  s2_tag;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:99:29]
  reg         io_f3_resp_0_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:107:38]
  reg  [1:0]  io_f3_resp_0_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:108:38]
  reg  [2:0]  io_f3_resp_0_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:38]
  reg         io_f3_resp_1_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:107:38]
  reg  [1:0]  io_f3_resp_1_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:108:38]
  reg  [2:0]  io_f3_resp_1_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:38]
  reg         io_f3_resp_2_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:107:38]
  reg  [1:0]  io_f3_resp_2_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:108:38]
  reg  [2:0]  io_f3_resp_2_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:38]
  reg         io_f3_resp_3_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:107:38]
  reg  [1:0]  io_f3_resp_3_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:108:38]
  reg  [2:0]  io_f3_resp_3_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:38]
  reg  [19:0] clear_u_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:112:28]
  wire        doing_clear_u = clear_u_ctr[11:0] == 12'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:112:28, :115:{34,61}]
  wire [1:0]  _GEN = io_update_pc[4:3] ^ io_update_hist[1:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :60:29, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
  wire [6:0]  update_idx = {io_update_pc[9:5], _GEN};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:{29,43}]
  wire [1:0]  _GEN_0 = io_update_pc[11:10] ^ io_update_hist[1:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :62:{30,50}, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
  wire [6:0]  update_tag = {io_update_pc[16:12], _GEN_0};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:{50,64}]
  assign table_MPORT_data_0 = doing_reset ? 11'h0 : {1'h1, io_update_pc[16:12], _GEN_0, update_wdata_0_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:{50,64}, :72:28, :124:{8,102}, :149:33]
  assign table_MPORT_data_1 = doing_reset ? 11'h0 : {1'h1, io_update_pc[16:12], _GEN_0, update_wdata_1_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:{50,64}, :72:28, :124:{8,102}, :149:33]
  assign table_MPORT_data_2 = doing_reset ? 11'h0 : {1'h1, io_update_pc[16:12], _GEN_0, update_wdata_2_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:{50,64}, :72:28, :124:{8,102}, :149:33]
  assign table_MPORT_data_3 = doing_reset ? 11'h0 : {1'h1, io_update_pc[16:12], _GEN_0, update_wdata_3_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:{50,64}, :72:28, :124:{8,102}, :149:33]
  wire        _GEN_1 = doing_reset | doing_clear_u;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :115:61, :131:21]
  assign tage_us_MPORT_1_data_0 = _GEN_1 ? 4'h0 : update_u_wdata_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:{8,21}, :160:27]
  assign tage_us_MPORT_1_data_1 = _GEN_1 ? 4'h0 : update_u_wdata_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:{8,21}, :160:27]
  assign tage_us_MPORT_1_data_2 = _GEN_1 ? 4'h0 : update_u_wdata_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:{8,21}, :160:27]
  assign tage_us_MPORT_1_data_3 = _GEN_1 ? 4'h0 : update_u_wdata_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:{8,21}, :160:27]
  reg  [6:0]  wrbypass_tags_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29]
  reg  [6:0]  wrbypass_tags_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29]
  reg  [6:0]  wrbypass_idxs_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:136:29]
  reg  [6:0]  wrbypass_idxs_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:136:29]
  reg  [2:0]  wrbypass_0_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_0_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_0_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_0_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_1_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_1_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_1_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg  [2:0]  wrbypass_1_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29]
  reg         wrbypass_enq_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:138:33]
  wire        wrbypass_hits_0 = ~doing_reset & wrbypass_tags_0 == update_tag & wrbypass_idxs_0 == update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43, :62:64, :72:28, :103:83, :135:29, :136:29, :141:18, :142:{22,37}, :143:22]
  wire        wrbypass_hit = wrbypass_hits_0 | ~doing_reset & wrbypass_tags_1 == update_tag & wrbypass_idxs_1 == update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43, :62:64, :72:28, :103:83, :135:29, :136:29, :141:18, :142:{22,37}, :143:22, :145:48]
  wire [2:0]  _GEN_2 = wrbypass_hits_0 ? wrbypass_0_0 : wrbypass_1_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :137:29, :141:18, :142:37]
  wire [2:0]  _GEN_3 = wrbypass_hits_0 ? wrbypass_0_1 : wrbypass_1_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :137:29, :141:18, :142:37]
  wire [2:0]  _GEN_4 = wrbypass_hits_0 ? wrbypass_0_2 : wrbypass_1_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :137:29, :141:18, :142:37]
  wire [2:0]  _GEN_5 = wrbypass_hits_0 ? wrbypass_0_3 : wrbypass_1_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :137:29, :141:18, :142:37]
  assign update_wdata_0_ctr = io_update_alloc_0 ? (io_update_taken_0 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_0 ? ((&_GEN_2) ? 3'h7 : _GEN_2 + 3'h1) : _GEN_2 == 3'h0 ? 3'h0 : _GEN_2 - 3'h1) : io_update_taken_0 ? ((&io_update_old_ctr_0) ? 3'h7 : io_update_old_ctr_0 + 3'h1) : io_update_old_ctr_0 == 3'h0 ? 3'h0 : io_update_old_ctr_0 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :145:48, :149:33, :150:10, :153:10]
  assign update_u_wdata_0 = {2'h0, io_update_u_0};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :160:27]
  assign update_wdata_1_ctr = io_update_alloc_1 ? (io_update_taken_1 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_1 ? ((&_GEN_3) ? 3'h7 : _GEN_3 + 3'h1) : _GEN_3 == 3'h0 ? 3'h0 : _GEN_3 - 3'h1) : io_update_taken_1 ? ((&io_update_old_ctr_1) ? 3'h7 : io_update_old_ctr_1 + 3'h1) : io_update_old_ctr_1 == 3'h0 ? 3'h0 : io_update_old_ctr_1 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :145:48, :149:33, :150:10, :153:10]
  assign update_u_wdata_1 = {2'h0, io_update_u_1};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :160:27]
  assign update_wdata_2_ctr = io_update_alloc_2 ? (io_update_taken_2 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_2 ? ((&_GEN_4) ? 3'h7 : _GEN_4 + 3'h1) : _GEN_4 == 3'h0 ? 3'h0 : _GEN_4 - 3'h1) : io_update_taken_2 ? ((&io_update_old_ctr_2) ? 3'h7 : io_update_old_ctr_2 + 3'h1) : io_update_old_ctr_2 == 3'h0 ? 3'h0 : io_update_old_ctr_2 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :145:48, :149:33, :150:10, :153:10]
  assign update_u_wdata_2 = {2'h0, io_update_u_2};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :160:27]
  assign update_wdata_3_ctr = io_update_alloc_3 ? (io_update_taken_3 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_3 ? ((&_GEN_5) ? 3'h7 : _GEN_5 + 3'h1) : _GEN_5 == 3'h0 ? 3'h0 : _GEN_5 - 3'h1) : io_update_taken_3 ? ((&io_update_old_ctr_3) ? 3'h7 : io_update_old_ctr_3 + 3'h1) : io_update_old_ctr_3 == 3'h0 ? 3'h0 : io_update_old_ctr_3 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :145:48, :149:33, :150:10, :153:10]
  assign update_u_wdata_3 = {2'h0, io_update_u_3};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :160:27]
  wire        _GEN_6 = io_update_mask_0 | io_update_mask_1 | io_update_mask_2 | io_update_mask_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:163:32]
  wire        _GEN_7 = ~_GEN_6 | wrbypass_hit | wrbypass_enq_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :138:33, :145:48, :163:{32,38}, :164:39, :168:39]
  wire        _GEN_8 = ~_GEN_6 | wrbypass_hit | ~wrbypass_enq_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :138:33, :145:48, :163:{32,38}, :164:39, :168:39]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      doing_reset <= 1'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28]
      reset_idx <= 7'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:73:26]
      clear_u_ctr <= 20'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:112:28]
      wrbypass_enq_idx <= 1'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:138:33]
    end
    else begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      doing_reset <= reset_idx != 7'h7F & doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :73:26, :75:{19,36,50}]
      reset_idx <= reset_idx + {6'h0, doing_reset};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :73:26, :74:26]
      clear_u_ctr <= doing_reset ? 20'h1 : clear_u_ctr + 20'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :112:28, :113:{22,36,70,85}]
      if (~_GEN_6 | wrbypass_hit) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :138:33, :145:48, :163:{32,38}, :164:39]
      end
      else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:138:33, :163:38, :164:39]
        wrbypass_enq_idx <= wrbypass_enq_idx - 1'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:138:33, generators/boom/src/main/scala/v3/util/util.scala:203:14]
    end
    s2_tag <= {io_f1_req_pc[16:12], io_f1_req_pc[11:10] ^ io_f1_req_ghist[1:0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :62:{30,50,64}, :99:29, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
    io_f3_resp_0_valid_REG <= _table_R0_data[10] & _table_R0_data[9:3] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :95:27, :99:29, :101:87, :103:{60,69,80,83}, :107:38]
    io_f3_resp_0_bits_u_REG <= _tage_us_R0_data[1:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28, :108:{38,52}]
    io_f3_resp_0_bits_ctr_REG <= _table_R0_data[2:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27, :101:87, :109:38]
    io_f3_resp_1_valid_REG <= _table_R0_data[21] & _table_R0_data[20:14] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :95:27, :99:29, :101:87, :103:{60,69,80,83}, :107:38]
    io_f3_resp_1_bits_u_REG <= _tage_us_R0_data[5:4];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28, :108:{38,52}]
    io_f3_resp_1_bits_ctr_REG <= _table_R0_data[13:11];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27, :101:87, :109:38]
    io_f3_resp_2_valid_REG <= _table_R0_data[32] & _table_R0_data[31:25] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :95:27, :99:29, :101:87, :103:{60,69,80,83}, :107:38]
    io_f3_resp_2_bits_u_REG <= _tage_us_R0_data[9:8];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28, :108:{38,52}]
    io_f3_resp_2_bits_ctr_REG <= _table_R0_data[24:22];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27, :101:87, :109:38]
    io_f3_resp_3_valid_REG <= _table_R0_data[43] & _table_R0_data[42:36] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :95:27, :99:29, :101:87, :103:{60,69,80,83}, :107:38]
    io_f3_resp_3_bits_u_REG <= _tage_us_R0_data[13:12];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28, :108:{38,52}]
    io_f3_resp_3_bits_ctr_REG <= _table_R0_data[35:33];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27, :101:87, :109:38]
    if (_GEN_7) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :163:38, :164:39, :168:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :163:38, :164:39, :168:39]
      wrbypass_tags_0 <= update_tag;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:64, :135:29]
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :163:38, :164:39, :168:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :163:38, :164:39, :168:39]
      wrbypass_tags_1 <= update_tag;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:64, :135:29]
    if (_GEN_7) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :136:29, :163:38, :164:39, :168:39, :169:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:136:29, :163:38, :164:39, :169:39]
      wrbypass_idxs_0 <= update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43, :136:29]
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:135:29, :136:29, :163:38, :164:39, :168:39, :169:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:136:29, :163:38, :164:39, :169:39]
      wrbypass_idxs_1 <= update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43, :136:29]
    if (_GEN_6) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:163:32]
      if (wrbypass_hit) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:145:48]
        if (wrbypass_hits_0) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:18, :142:37]
          wrbypass_0_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
          wrbypass_0_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
          wrbypass_0_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
          wrbypass_0_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        end
        else begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:18, :142:37]
          wrbypass_1_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
          wrbypass_1_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
          wrbypass_1_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
          wrbypass_1_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        end
      end
      else if (wrbypass_enq_idx) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:138:33]
        wrbypass_1_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        wrbypass_1_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        wrbypass_1_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        wrbypass_1_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
      end
      else begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:138:33]
        wrbypass_0_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        wrbypass_0_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        wrbypass_0_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
        wrbypass_0_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:29, :149:33]
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    initial begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        end	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        doing_reset = _RANDOM[2'h0][0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28]
        reset_idx = _RANDOM[2'h0][7:1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :73:26]
        s2_tag = _RANDOM[2'h0][14:8];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :99:29]
        io_f3_resp_0_valid_REG = _RANDOM[2'h0][15];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :107:38]
        io_f3_resp_0_bits_u_REG = _RANDOM[2'h0][17:16];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :108:38]
        io_f3_resp_0_bits_ctr_REG = _RANDOM[2'h0][20:18];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :109:38]
        io_f3_resp_1_valid_REG = _RANDOM[2'h0][21];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :107:38]
        io_f3_resp_1_bits_u_REG = _RANDOM[2'h0][23:22];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :108:38]
        io_f3_resp_1_bits_ctr_REG = _RANDOM[2'h0][26:24];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :109:38]
        io_f3_resp_2_valid_REG = _RANDOM[2'h0][27];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :107:38]
        io_f3_resp_2_bits_u_REG = _RANDOM[2'h0][29:28];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :108:38]
        io_f3_resp_2_bits_ctr_REG = {_RANDOM[2'h0][31:30], _RANDOM[2'h1][0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :109:38]
        io_f3_resp_3_valid_REG = _RANDOM[2'h1][1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :107:38, :109:38]
        io_f3_resp_3_bits_u_REG = _RANDOM[2'h1][3:2];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :108:38, :109:38]
        io_f3_resp_3_bits_ctr_REG = _RANDOM[2'h1][6:4];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38]
        clear_u_ctr = _RANDOM[2'h1][26:7];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38, :112:28]
        wrbypass_tags_0 = {_RANDOM[2'h1][31:27], _RANDOM[2'h2][1:0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38, :135:29]
        wrbypass_tags_1 = _RANDOM[2'h2][8:2];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :135:29]
        wrbypass_idxs_0 = _RANDOM[2'h2][15:9];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :135:29, :136:29]
        wrbypass_idxs_1 = _RANDOM[2'h2][22:16];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :135:29, :136:29]
        wrbypass_0_0 = _RANDOM[2'h2][25:23];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :135:29, :137:29]
        wrbypass_0_1 = _RANDOM[2'h2][28:26];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :135:29, :137:29]
        wrbypass_0_2 = _RANDOM[2'h2][31:29];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :135:29, :137:29]
        wrbypass_0_3 = _RANDOM[2'h3][2:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :137:29]
        wrbypass_1_0 = _RANDOM[2'h3][5:3];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :137:29]
        wrbypass_1_1 = _RANDOM[2'h3][8:6];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :137:29]
        wrbypass_1_2 = _RANDOM[2'h3][11:9];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :137:29]
        wrbypass_1_3 = _RANDOM[2'h3][14:12];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :137:29]
        wrbypass_enq_idx = _RANDOM[2'h3][15];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :137:29, :138:33]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  tage_us tage_us (	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28]
    .R0_addr (s1_hashed_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43]
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_tage_us_R0_data),
    .W0_addr (doing_reset ? reset_idx : doing_clear_u ? clear_u_ctr[18:12] : {io_update_pc[9:5], _GEN}),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:{29,43}, :72:28, :73:26, :112:28, :115:61, :116:33, :130:{8,36}]
    .W0_clk  (clock),
    .W0_data ({tage_us_MPORT_1_data_3, tage_us_MPORT_1_data_2, tage_us_MPORT_1_data_1, tage_us_MPORT_1_data_0}),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28, :131:8]
    .W0_mask (_GEN_1 ? 4'hF : {io_update_u_mask_3, io_update_u_mask_2, io_update_u_mask_1, io_update_u_mask_0})	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:21, :132:{8,77}]
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:94:28]
  table_0 table_0 (	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27]
    .R0_addr (s1_hashed_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43]
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_table_R0_data),
    .W0_addr (doing_reset ? reset_idx : update_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:43, :72:28, :73:26, :123:8]
    .W0_clk  (clock),
    .W0_data ({table_MPORT_data_3, table_MPORT_data_2, table_MPORT_data_1, table_MPORT_data_0}),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27, :124:8]
    .W0_mask (doing_reset ? 4'hF : {io_update_mask_3, io_update_mask_2, io_update_mask_1, io_update_mask_0})	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :125:{8,90}]
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:27]
  assign io_f3_resp_0_valid = io_f3_resp_0_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :107:38]
  assign io_f3_resp_0_bits_ctr = io_f3_resp_0_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38]
  assign io_f3_resp_0_bits_u = io_f3_resp_0_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :108:38]
  assign io_f3_resp_1_valid = io_f3_resp_1_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :107:38]
  assign io_f3_resp_1_bits_ctr = io_f3_resp_1_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38]
  assign io_f3_resp_1_bits_u = io_f3_resp_1_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :108:38]
  assign io_f3_resp_2_valid = io_f3_resp_2_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :107:38]
  assign io_f3_resp_2_bits_ctr = io_f3_resp_2_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38]
  assign io_f3_resp_2_bits_u = io_f3_resp_2_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :108:38]
  assign io_f3_resp_3_valid = io_f3_resp_3_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :107:38]
  assign io_f3_resp_3_bits_ctr = io_f3_resp_3_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :109:38]
  assign io_f3_resp_3_bits_u = io_f3_resp_3_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :108:38]
endmodule

