// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomMulAddRecFNPipe3_e11_s53(	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
  input         io_validin,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  input  [1:0]  io_op,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  input  [64:0] io_a,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  input  [64:0] io_b,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  input  [64:0] io_c,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  input  [2:0]  io_roundingMode,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  output [64:0] io_out,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  output [4:0]  io_exceptionFlags,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
  output        io_validout	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
);

  wire [64:0]  _roundRawFNToRecFN_io_out;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:322:33]
  wire [4:0]   _roundRawFNToRecFN_io_exceptionFlags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:322:33]
  wire         _mulAddRecFNToRaw_postMul_io_invalidExc;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire         _mulAddRecFNToRaw_postMul_io_rawOut_isNaN;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire         _mulAddRecFNToRaw_postMul_io_rawOut_isInf;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire         _mulAddRecFNToRaw_postMul_io_rawOut_isZero;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire         _mulAddRecFNToRaw_postMul_io_rawOut_sign;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire [12:0]  _mulAddRecFNToRaw_postMul_io_rawOut_sExp;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire [55:0]  _mulAddRecFNToRaw_postMul_io_rawOut_sig;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  wire [52:0]  _mulAddRecFNToRaw_preMul_io_mulAddA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire [52:0]  _mulAddRecFNToRaw_preMul_io_mulAddB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire [105:0] _mulAddRecFNToRaw_preMul_io_mulAddC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isSigNaNAny;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isNaNAOrB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isInfA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isInfB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_signProd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isNaNC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isInfC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire [12:0]  _mulAddRecFNToRaw_preMul_io_toPostMul_sExpSum;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_doSubMags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_CIsDominant;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire [5:0]   _mulAddRecFNToRaw_preMul_io_toPostMul_CDom_CAlignDist;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire [54:0]  _mulAddRecFNToRaw_preMul_io_toPostMul_highAlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  wire         _mulAddRecFNToRaw_preMul_io_toPostMul_bit0AlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  reg          s1_mulAddA_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [52:0]  s1_mulAddA_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [52:0]  s1_mulAddB_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [105:0] s1_mulAddC_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isSigNaNAny;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isNaNAOrB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isInfA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isZeroA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isInfB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isZeroB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_signProd;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isNaNC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isInfC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_isZeroC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [12:0]  s1_toPostMul_pipe_b_sExpSum;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_doSubMags;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_CIsDominant;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [5:0]   s1_toPostMul_pipe_b_CDom_CAlignDist;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [54:0]  s1_toPostMul_pipe_b_highAlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_toPostMul_pipe_b_bit0AlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [2:0]   s1_rm_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_mulAddResult_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [106:0] s2_mulAddResult_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isSigNaNAny;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isNaNAOrB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isInfA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isZeroA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isInfB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isZeroB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_signProd;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isNaNC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isInfC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_isZeroC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [12:0]  s2_toPostMul_pipe_b_sExpSum;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_doSubMags;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_CIsDominant;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [5:0]   s2_toPostMul_pipe_b_CDom_CAlignDist;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [54:0]  s2_toPostMul_pipe_b_highAlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_toPostMul_pipe_b_bit0AlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [2:0]   s2_rm_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s3_out_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [64:0]  s3_out_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [4:0]   s3_exc_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
      s1_mulAddA_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s2_mulAddResult_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s3_out_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
      s1_mulAddA_pipe_v <= io_validin;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s2_mulAddResult_pipe_v <= s1_mulAddA_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s3_out_pipe_v <= s2_mulAddResult_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
    end
    if (io_validin) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:279:14]
      s1_mulAddA_pipe_b <= _mulAddRecFNToRaw_preMul_io_mulAddA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_mulAddB_pipe_b <= _mulAddRecFNToRaw_preMul_io_mulAddB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_mulAddC_pipe_b <= _mulAddRecFNToRaw_preMul_io_mulAddC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isSigNaNAny <= _mulAddRecFNToRaw_preMul_io_toPostMul_isSigNaNAny;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isNaNAOrB <= _mulAddRecFNToRaw_preMul_io_toPostMul_isNaNAOrB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isInfA <= _mulAddRecFNToRaw_preMul_io_toPostMul_isInfA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isZeroA <= _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isInfB <= _mulAddRecFNToRaw_preMul_io_toPostMul_isInfB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isZeroB <= _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_signProd <= _mulAddRecFNToRaw_preMul_io_toPostMul_signProd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isNaNC <= _mulAddRecFNToRaw_preMul_io_toPostMul_isNaNC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isInfC <= _mulAddRecFNToRaw_preMul_io_toPostMul_isInfC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_isZeroC <= _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_sExpSum <= _mulAddRecFNToRaw_preMul_io_toPostMul_sExpSum;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_doSubMags <= _mulAddRecFNToRaw_preMul_io_toPostMul_doSubMags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_CIsDominant <= _mulAddRecFNToRaw_preMul_io_toPostMul_CIsDominant;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_CDom_CAlignDist <= _mulAddRecFNToRaw_preMul_io_toPostMul_CDom_CAlignDist;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_highAlignedSigC <= _mulAddRecFNToRaw_preMul_io_toPostMul_highAlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_toPostMul_pipe_b_bit0AlignedSigC <= _mulAddRecFNToRaw_preMul_io_toPostMul_bit0AlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_rm_pipe_b <= io_roundingMode;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (s1_mulAddA_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s2_mulAddResult_pipe_b <= {1'h0, {53'h0, s1_mulAddA_pipe_b} * {53'h0, s1_mulAddB_pipe_b}} + {1'h0, s1_mulAddC_pipe_b};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:{39,58}, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isSigNaNAny <= s1_toPostMul_pipe_b_isSigNaNAny;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isNaNAOrB <= s1_toPostMul_pipe_b_isNaNAOrB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isInfA <= s1_toPostMul_pipe_b_isInfA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isZeroA <= s1_toPostMul_pipe_b_isZeroA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isInfB <= s1_toPostMul_pipe_b_isInfB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isZeroB <= s1_toPostMul_pipe_b_isZeroB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_signProd <= s1_toPostMul_pipe_b_signProd;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isNaNC <= s1_toPostMul_pipe_b_isNaNC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isInfC <= s1_toPostMul_pipe_b_isInfC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_isZeroC <= s1_toPostMul_pipe_b_isZeroC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_sExpSum <= s1_toPostMul_pipe_b_sExpSum;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_doSubMags <= s1_toPostMul_pipe_b_doSubMags;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_CIsDominant <= s1_toPostMul_pipe_b_CIsDominant;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_CDom_CAlignDist <= s1_toPostMul_pipe_b_CDom_CAlignDist;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_highAlignedSigC <= s1_toPostMul_pipe_b_highAlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_pipe_b_bit0AlignedSigC <= s1_toPostMul_pipe_b_bit0AlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_rm_pipe_b <= s1_rm_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (s2_mulAddResult_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s3_out_pipe_b <= _roundRawFNToRecFN_io_out;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:322:33, src/main/scala/chisel3/util/Valid.scala:142:26]
      s3_exc_pipe_b <= _roundRawFNToRecFN_io_exceptionFlags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:322:33, src/main/scala/chisel3/util/Valid.scala:142:26]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:18];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
        end	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
        s1_mulAddA_pipe_v = _RANDOM[5'h0][0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:141:24]
        s1_mulAddA_pipe_b = {_RANDOM[5'h0][31:1], _RANDOM[5'h1][21:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        s1_mulAddB_pipe_b = {_RANDOM[5'h1][31:23], _RANDOM[5'h2], _RANDOM[5'h3][11:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_mulAddC_pipe_b = {_RANDOM[5'h3][31:13], _RANDOM[5'h4], _RANDOM[5'h5], _RANDOM[5'h6][22:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isSigNaNAny = _RANDOM[5'h6][24];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isNaNAOrB = _RANDOM[5'h6][25];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isInfA = _RANDOM[5'h6][26];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isZeroA = _RANDOM[5'h6][27];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isInfB = _RANDOM[5'h6][28];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isZeroB = _RANDOM[5'h6][29];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_signProd = _RANDOM[5'h6][30];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isNaNC = _RANDOM[5'h6][31];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isInfC = _RANDOM[5'h7][0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_isZeroC = _RANDOM[5'h7][1];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_sExpSum = _RANDOM[5'h7][14:2];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_doSubMags = _RANDOM[5'h7][15];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_CIsDominant = _RANDOM[5'h7][16];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_CDom_CAlignDist = _RANDOM[5'h7][22:17];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_highAlignedSigC = {_RANDOM[5'h7][31:23], _RANDOM[5'h8], _RANDOM[5'h9][13:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_toPostMul_pipe_b_bit0AlignedSigC = _RANDOM[5'h9][14];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_rm_pipe_b = _RANDOM[5'h9][18:16];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_mulAddResult_pipe_v = _RANDOM[5'h9][21];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        s2_mulAddResult_pipe_b = {_RANDOM[5'h9][31:22], _RANDOM[5'hA], _RANDOM[5'hB], _RANDOM[5'hC], _RANDOM[5'hD][0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isSigNaNAny = _RANDOM[5'hD][2];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isNaNAOrB = _RANDOM[5'hD][3];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isInfA = _RANDOM[5'hD][4];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isZeroA = _RANDOM[5'hD][5];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isInfB = _RANDOM[5'hD][6];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isZeroB = _RANDOM[5'hD][7];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_signProd = _RANDOM[5'hD][8];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isNaNC = _RANDOM[5'hD][9];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isInfC = _RANDOM[5'hD][10];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_isZeroC = _RANDOM[5'hD][11];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_sExpSum = _RANDOM[5'hD][24:12];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_doSubMags = _RANDOM[5'hD][25];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_CIsDominant = _RANDOM[5'hD][26];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_CDom_CAlignDist = {_RANDOM[5'hD][31:27], _RANDOM[5'hE][0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_highAlignedSigC = {_RANDOM[5'hE][31:1], _RANDOM[5'hF][23:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_pipe_b_bit0AlignedSigC = _RANDOM[5'hF][24];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_rm_pipe_b = _RANDOM[5'hF][28:26];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s3_out_pipe_v = _RANDOM[5'hF][31];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        s3_out_pipe_b = {_RANDOM[5'h10], _RANDOM[5'h11], _RANDOM[5'h12][0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s3_exc_pipe_b = _RANDOM[5'h12][6:2];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MulAddRecFNToRaw_preMul_e11_s53 mulAddRecFNToRaw_preMul (	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
    .io_op                        (io_op),
    .io_a                         (io_a),
    .io_b                         (io_b),
    .io_c                         (io_c),
    .io_mulAddA                   (_mulAddRecFNToRaw_preMul_io_mulAddA),
    .io_mulAddB                   (_mulAddRecFNToRaw_preMul_io_mulAddB),
    .io_mulAddC                   (_mulAddRecFNToRaw_preMul_io_mulAddC),
    .io_toPostMul_isSigNaNAny     (_mulAddRecFNToRaw_preMul_io_toPostMul_isSigNaNAny),
    .io_toPostMul_isNaNAOrB       (_mulAddRecFNToRaw_preMul_io_toPostMul_isNaNAOrB),
    .io_toPostMul_isInfA          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfA),
    .io_toPostMul_isZeroA         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroA),
    .io_toPostMul_isInfB          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfB),
    .io_toPostMul_isZeroB         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroB),
    .io_toPostMul_signProd        (_mulAddRecFNToRaw_preMul_io_toPostMul_signProd),
    .io_toPostMul_isNaNC          (_mulAddRecFNToRaw_preMul_io_toPostMul_isNaNC),
    .io_toPostMul_isInfC          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfC),
    .io_toPostMul_isZeroC         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroC),
    .io_toPostMul_sExpSum         (_mulAddRecFNToRaw_preMul_io_toPostMul_sExpSum),
    .io_toPostMul_doSubMags       (_mulAddRecFNToRaw_preMul_io_toPostMul_doSubMags),
    .io_toPostMul_CIsDominant     (_mulAddRecFNToRaw_preMul_io_toPostMul_CIsDominant),
    .io_toPostMul_CDom_CAlignDist (_mulAddRecFNToRaw_preMul_io_toPostMul_CDom_CAlignDist),
    .io_toPostMul_highAlignedSigC (_mulAddRecFNToRaw_preMul_io_toPostMul_highAlignedSigC),
    .io_toPostMul_bit0AlignedSigC (_mulAddRecFNToRaw_preMul_io_toPostMul_bit0AlignedSigC)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:293:39]
  MulAddRecFNToRaw_postMul_e11_s53 mulAddRecFNToRaw_postMul (	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_fromPreMul_isSigNaNAny     (s2_toPostMul_pipe_b_isSigNaNAny),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isNaNAOrB       (s2_toPostMul_pipe_b_isNaNAOrB),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isInfA          (s2_toPostMul_pipe_b_isInfA),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isZeroA         (s2_toPostMul_pipe_b_isZeroA),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isInfB          (s2_toPostMul_pipe_b_isInfB),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isZeroB         (s2_toPostMul_pipe_b_isZeroB),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_signProd        (s2_toPostMul_pipe_b_signProd),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isNaNC          (s2_toPostMul_pipe_b_isNaNC),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isInfC          (s2_toPostMul_pipe_b_isInfC),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_isZeroC         (s2_toPostMul_pipe_b_isZeroC),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_sExpSum         (s2_toPostMul_pipe_b_sExpSum),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_doSubMags       (s2_toPostMul_pipe_b_doSubMags),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_CIsDominant     (s2_toPostMul_pipe_b_CIsDominant),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_CDom_CAlignDist (s2_toPostMul_pipe_b_CDom_CAlignDist),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_highAlignedSigC (s2_toPostMul_pipe_b_highAlignedSigC),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_fromPreMul_bit0AlignedSigC (s2_toPostMul_pipe_b_bit0AlignedSigC),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_mulAddResult               (s2_mulAddResult_pipe_b),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_roundingMode               (s2_rm_pipe_b),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_invalidExc                 (_mulAddRecFNToRaw_postMul_io_invalidExc),
    .io_rawOut_isNaN               (_mulAddRecFNToRaw_postMul_io_rawOut_isNaN),
    .io_rawOut_isInf               (_mulAddRecFNToRaw_postMul_io_rawOut_isInf),
    .io_rawOut_isZero              (_mulAddRecFNToRaw_postMul_io_rawOut_isZero),
    .io_rawOut_sign                (_mulAddRecFNToRaw_postMul_io_rawOut_sign),
    .io_rawOut_sExp                (_mulAddRecFNToRaw_postMul_io_rawOut_sExp),
    .io_rawOut_sig                 (_mulAddRecFNToRaw_postMul_io_rawOut_sig)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
  RoundRawFNToRecFN_e11_s53 roundRawFNToRecFN (	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:322:33]
    .io_invalidExc     (_mulAddRecFNToRaw_postMul_io_invalidExc),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_infiniteExc    (1'h0),
    .io_in_isNaN       (_mulAddRecFNToRaw_postMul_io_rawOut_isNaN),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_in_isInf       (_mulAddRecFNToRaw_postMul_io_rawOut_isInf),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_in_isZero      (_mulAddRecFNToRaw_postMul_io_rawOut_isZero),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_in_sign        (_mulAddRecFNToRaw_postMul_io_rawOut_sign),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_in_sExp        (_mulAddRecFNToRaw_postMul_io_rawOut_sExp),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_in_sig         (_mulAddRecFNToRaw_postMul_io_rawOut_sig),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:317:40]
    .io_roundingMode   (s2_rm_pipe_b),	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    .io_out            (_roundRawFNToRecFN_io_out),
    .io_exceptionFlags (_roundRawFNToRecFN_io_exceptionFlags)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:322:33]
  assign io_out = s3_out_pipe_b;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
  assign io_exceptionFlags = s3_exc_pipe_b;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:142:26]
  assign io_validout = s3_out_pipe_v;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:275:7, src/main/scala/chisel3/util/Valid.scala:141:24]
endmodule

