yosys -import
setundef -zero
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ALUExeUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ALUExeUnit_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ALUExeUnit_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ALUUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ALUUnit_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AMOALU.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AXI4IdIndexer.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AXI4UserYanker.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter1_Bool.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_BoomDCacheReqInternal.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_BranchPredictionUpdate.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_ExeUnitResp.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_ExeUnitResp_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_L1DataWriteReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_L1MetaReadReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_L1MetaWriteReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_LineBufferReadReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_LineBufferWriteReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_TLBundleC_a32d64s2k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter2_WritebackReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter3_BoomDCacheResp.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter3_BoomL1DataReadReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter3_UInt5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter3_Valid_PTWReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Arbiter6_BoomL1MetaReadReq.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueue.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSink_DebugInternalBundle.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSink_Phit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSink_Phit_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSink_TLBundleA_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSink_TLBundleD_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSource_DebugInternalBundle.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSource_Phit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSource_Phit_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSource_TLBundleA_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueueSource_TLBundleD_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncQueue_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetRegVec_w1_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetRegVec_w1_i1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetRegVec_w2_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerShiftReg_w1_d3_i0_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerShiftReg_w1_d3_i0_1_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerShiftReg_w1_d3_i0_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerShiftReg_w4_d3_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncResetSynchronizerShiftReg_w4_d3_i0_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncValidSync.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/AsyncValidSync_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Atomics.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BIMBranchPredictorBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BTBBranchPredictorBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BankBinder.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BankedStore.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BasicDispatcher.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomCore.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomDuplicatedDataArray.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomFrontend.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomIOMSHR.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomMSHR.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomMSHRFile.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomNonBlockingDCache.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomProbeUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomRAS.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomTile.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BoomWritebackUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchDecode.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchKillableQueue.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchKillableQueue_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchKillableQueue_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchKillableQueue_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchKillableQueue_5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchMaskGenerationLogic.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BranchPredictor.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/BundleBridgeNexus_UInt1_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CLINT.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CLINTClockSinkDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CSRFile.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CaptureChain_JTAGIdcodeBundle.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CaptureUpdateChain_DMIAccessCapture_To_DMIAccessUpdate.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CaptureUpdateChain_DTMInfo_To_DTMInfo.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CaptureUpdateChain_UInt5_To_UInt5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ChipTop.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ChipyardPRCICtrlClockSinkDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockCrossingReg_w15.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockCrossingReg_w32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockCrossingReg_w32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockCrossingReg_w43.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockCrossingReg_w55.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockGroupAggregator_allClocks.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockGroupAsyncResetCoercer.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockGroupCombiner.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ClockGroupResetSynchronizer.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CoherenceManagerWrapper.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/CompareRecFN.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ComposedBranchPredictorBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DMIToTL.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DebugTransportModuleJTAG.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DecodeUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DecoupledSerialPhy.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DecoupledSerialPhy_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DigitalTop.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Directory.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DivSqrtRecF64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DivSqrtRecF64ToRaw_mulAddZ31.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DivSqrtRecF64_mulAddZ31.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/DivUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/EICG_wrapper.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ErrorDeviceWrapper.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FAMicroBTBBranchPredictorBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FDivSqrtUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FMADecoder.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPToFP.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPToInt.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPU.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPUExeUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPUFMAPipe_l4_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPUFMAPipe_l4_f64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FPUUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FetchBuffer.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FetchTargetQueue.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FixedClockBroadcast_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FixedClockBroadcast_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FixedClockBroadcast_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FixedClockBroadcast_7.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FlitToPhit_f32_p32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FlitToPhit_f32_p32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ForwardingAgeLogic.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FpPipeline.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/FrontBus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw10_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw10_f32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw67_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw67_f32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw87_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw87_f32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw88_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDeserializer_TLBeatw88_f32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDigitalInIOCell.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericDigitalOutIOCell.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericSerializer_TLBeatw10_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericSerializer_TLBeatw67_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericSerializer_TLBeatw87_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/GenericSerializer_TLBeatw88_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/HellaCacheArbiter.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ICache.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IDPool.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/INToRecFN_i64_e11_s53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/INToRecFN_i64_e8_s24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ITLB.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/InclusiveCache.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/InclusiveCacheBankScheduler.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/InclusiveCacheControl.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/InferredResetSynchronizerPrimitiveShiftReg_d3_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntSyncAsyncCrossingSink_n1x1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntSyncCrossingSource_n1x1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntSyncCrossingSource_n1x1_Registered.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntSyncCrossingSource_n1x2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntSyncSyncCrossingSink_n1x1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntSyncSyncCrossingSink_n1x2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntToFP.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntToFPUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IntXbar_i4_o1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IssueSlot.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IssueSlot_16.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IssueUnitCollapsing.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IssueUnitCollapsing_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/IssueUnitCollapsing_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/JtagBypassChain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/JtagStateMachine.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/JtagTapController.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/L1MetadataArray.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/LSU.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/LevelGateway.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ListBuffer_PutBufferAEntry_q40_e40.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ListBuffer_PutBufferCEntry_q2_e16.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ListBuffer_QueuedRequest_q21_e33.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/LoopBranchPredictorBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/LoopBranchPredictorColumn.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MSHR.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MaxPeriodFibonacciLFSR.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MaxPeriodFibonacciLFSR_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MemAddrCalcUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MemoryBus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Mul54.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulAddRecFNPipe_l2_e11_s53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulAddRecFNPipe_l2_e8_s24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulAddRecFNToRaw_postMul_e11_s53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulAddRecFNToRaw_postMul_e8_s24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulAddRecFNToRaw_preMul_e11_s53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulAddRecFNToRaw_preMul_e8_s24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/MulDiv.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/NBDTLB.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/NonSyncResetSynchronizerPrimitiveShiftReg_d3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/OptimizationBarrier_EntryData.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/OptimizationBarrier_PTE.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/OptimizationBarrier_TLBEntryData.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/OptimizationBarrier_UInt.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PLICClockSinkDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PLICFanIn.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PMAChecker.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PMPChecker_s3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PTW.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PeripheryBus_cbus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PeripheryBus_pbus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PhitArbiter_p32_f32_n5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PhitArbiter_p32_f32_n5_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PhitDemux_p32_f32_n5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PhitDemux_p32_f32_n5_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PhitToFlit_p32_f32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PhitToFlit_p32_f32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PipelinedMulUnit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/PipelinedMultiplier.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ProbePicker.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue12_TLBundleC_a32d64s3k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_AXI4BundleARW.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_AXI4BundleW.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_BankedStoreInnerAddress.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_BranchPredictionBundle.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_BundleMap.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_DirectoryWrite.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_FetchBundle.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_FrontendResp.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_RegMapperInput_i23_m8.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_RegMapperInput_i9_m8.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_SinkXRequest.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_SourceXRequest.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleA_a14d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleA_a26d64s11k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleA_a32d64s6k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleA_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleD_a26d64s11k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleD_a32d64s6k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue1_TLBundleD_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_BranchPredictionUpdate.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a14d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a21d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a28d64s4k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a29d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a29d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a32d64s1k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a32d64s3k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a32d64s3k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a32d64s4k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleA_a32d64s5k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleB_a32d64s3k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleC_a32d64s3k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleC_a32d64s6k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a14d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a21d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a28d64s4k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a29d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a29d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a32d64s1k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a32d64s3k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a32d64s3k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a32d64s4k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a32d64s5k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleD_a32d8s1k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleE_a32d64s3k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue2_TLBundleE_a32d64s3k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue3_BankedStoreInnerDecoded.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue8_Flit.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue8_Flit_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue8_UInt8.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Queue8_UInt8_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RVCExpander.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RecFNToIN_e11_s53_i32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RecFNToIN_e11_s53_i64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RecFNToRecFN.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RecFNToRecFN_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterFileSynthesizable.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterFileSynthesizable_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterRead.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterReadDecode.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterReadDecode_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterReadDecode_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterReadDecode_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RegisterRead_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameBusyTable.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameBusyTable_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameFreeList.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameFreeList_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameMapTable.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameMapTable_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameStage.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RenameStage_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a12d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a13d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a17d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a21d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a26d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a28d64s4k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a28d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleA_a29d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Repeater_TLBundleD_a32d64s1k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ResetCatchAndSync_d3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ResetCatchAndSync_d3_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ResetSynchronizerShiftReg_w1_d3_i0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/Rob.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RocketALU.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie11_is53_oe8_os24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie11_is55_oe11_os53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie11_is55_oe11_os53_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie7_is64_oe11_os53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie7_is64_oe8_os24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie8_is24_oe11_os53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundAnyRawFNToRecFN_ie8_is26_oe8_os24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundRawFNToRecFN_e11_s53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundRawFNToRecFN_e11_s53_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/RoundRawFNToRecFN_e8_s24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SBToTL.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ScratchpadBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SerialRAM.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SerialTL0ClockSinkDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SinkA.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SinkC.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SinkD.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SinkE.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SinkX.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SourceA.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SourceB.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SourceC.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SourceD.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SourceE.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SourceX.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SynchronizerShiftReg_w1_d3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/SystemBus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAFromBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAFromBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAToBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAsyncCrossingSink_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAsyncCrossingSource_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAtomicAutomata_cbus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLAtomicAutomata_pbus.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBFromBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBFromBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBToBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a14d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a21d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a26d64s11k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a28d64s4k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a28d64s4k1z3u_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a29d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a29d64s7k1z3u_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a29d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a32d64s1k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a32d64s3k3z4c_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a32d64s4k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a32d64s5k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBuffer_a32d64s6k3z3c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBusBypass.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLBusBypassBar.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLCFromBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLCFromBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLCToBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLCacheCork.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDFromBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDFromBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDToBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDebugModule.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDebugModuleInner.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDebugModuleInnerAsync.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDebugModuleOuter.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLDebugModuleOuterAsync.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLEFromBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLEFromBeat_serial_tl_0_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLEToBeat_SerialRAM_a64d64s8k8z8c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLError.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLError_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_BootAddrReg.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_CLINT.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_Debug.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_LLCCtrl.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_PLIC.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_ScratchpadBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_TileClockGater.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_TileResetSetter.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_UART.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLFragmenter_bootrom.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_cbus_to_bootrom.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_cbus_to_clint.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_cbus_to_debug.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_cbus_to_l2_ctrl.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_cbus_to_plic.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_cbus_to_prci_ctrl.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_fbus_from_debug_sb.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_fbus_from_port_named_serial_tl_0_in.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_mbus_to_memory_controller_port_named_axi4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_pbus_to_bootaddressreg.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLInterconnectCoupler_pbus_to_device_named_uart_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_10.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_11.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_12.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_13.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_14.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_15.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_16.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_17.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_18.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_19.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_20.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_21.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_22.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_23.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_24.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_25.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_26.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_27.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_28.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_29.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_30.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_31.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_33.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_34.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_35.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_36.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_37.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_38.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_39.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_40.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_41.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_42.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_43.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_44.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_45.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_46.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_47.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_48.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_49.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_50.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_51.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_52.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_54.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_55.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_56.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_57.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_58.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_59.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_6.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_60.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_61.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_7.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_8.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLMonitor_9.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLPLIC.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLRAM_ScratchpadBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLROM.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLSerdesser_SerialRAM.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLSerdesser_serial_tl_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLToAXI4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLUART.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLUARTClockSinkDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLWidthWidget1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_MasterXbar_BoomTile_i2_o1_a32d64s3k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_cbus_in_i2_o1_a29d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_cbus_out_i1_o8_a29d64s7k1z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_dmixbar_i1_o2_a9d32s1k1z2u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_fbus_i2_o1_a32d64s5k3z4u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_mbus_i1_o2_a32d64s4k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_pbus_out_i1_o2_a29d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_prcibus_i1_o2_a21d64s7k1z3u.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TLXbar_sbus_i2_o2_a32d64s6k3z4c.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TSIToTileLink.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageBranchPredictorBank.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageTable.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageTable_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageTable_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageTable_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageTable_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TageTable_5.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TestHarness.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TileClockGater.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TilePRCIDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/TileResetSetter.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UARTAdapter.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UARTRx.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UARTRx_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UARTTx.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UARTTx_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UOPCodeFDivDecoder.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/UOPCodeFPUDecoder.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/array_0_0_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/array_1_0_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/array_2_0_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/array_3_0_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/bootromClockSinkDomain.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/btb_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/btb_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_array_0_0_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_btb_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_cc_banks_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_cc_dir_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_dataArrayWay_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_data_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_ebtb_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_ghist_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_l2_tlb_ram_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_mem_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_meta_0_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_meta_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_rob_debug_inst_mem_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_table_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_table_1_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_table_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_tag_array_0_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cacti_tag_array_ext.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cc_banks_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cc_banks_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cc_banks_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cc_banks_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/cc_dir.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/chipyard.harness.TestHarness.MediumBoomV3Config.model.mems.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/chipyard.harness.TestHarness.MediumBoomV3Config.top.mems.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/data.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/dataArrayWay_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/dataArrayWay_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/dataArrayWay_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/dataArrayWay_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/data_16x65.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/data_33x45.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/data_40x73.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ebtb.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/extern_modules.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ghist_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ghist_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/head_21x6.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/head_2x4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/head_40x6.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/hi_us.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/hi_us_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/hi_us_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/hi_us_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/hi_us_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/hi_us_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/l2_tlb_ram_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lb_16x64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lo_us.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lo_us_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lo_us_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lo_us_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lo_us_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/lo_us_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/mem.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/meta_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/meta_0_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/meta_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/next_16x4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/next_33x6.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/next_40x6.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/plusarg_reader.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/plusarg_reader_TestHarness_UNIQUIFIED.v
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_12x109.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_12x78.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_14x78.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_16x46.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x10.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x104.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x110.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x112.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x114.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x116.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x117.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x118.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x119.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x120.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x281.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x53.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x79.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x79_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x80.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x81.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x82.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_2x83.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_3x78.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_4x65.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_8x8.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_8x8_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_data_3x64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_flit_8x32.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_flit_8x32_TestHarness_UNIQUIFIED.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/ram_sink_2x3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/regfile_64x65.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/regfile_80x64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/rob_debug_inst_mem.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/sdq_17x64.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/table_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/table_0_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/table_1.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/table_2.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/table_3.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/table_4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/tag_array.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/tag_array_0.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/tail_21x6.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/tail_2x4.sv
read_verilog -sv /scratch/perf_area_eff/baseline_area_v2/syn_obj/input_src/tail_40x6.sv
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_100C_1v65.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_100C_1v95.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v56.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v65.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v76.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95_ccsnoise.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v40.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_n40C_1v28.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_n40C_1v35.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_n40C_1v40.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_n40C_1v44.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_n40C_1v60_ccsnoise.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_n40C_1v76.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_100C_1v80.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_tt_tt_025C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_wrapped_ff_ff_100C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_wrapped_ff_ff_n40C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_wrapped_ss_ss_100C_1v60_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_wrapped_tt_tt_025C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped3_pad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped3_pad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped3_pad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped3_pad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped_pad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped_pad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped_pad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vdda_hvc_clamped_pad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vdda_hvc_clamped_pad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vdda_hvc_clamped_pad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vdda_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vddio_hvc_clamped_pad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vddio_hvc_clamped_pad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vddio_hvc_clamped_pad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vddio_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssa_hvc_clamped_pad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssa_hvc_clamped_pad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssa_hvc_clamped_pad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssa_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_ff_100C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_ff_n40C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_ss_100C_1v60_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_tt_025C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_tt_100C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_ff_100C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_ff_n40C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_ss_100C_1v60_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_tt_025C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_tt_100C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssio_hvc_clamped_pad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssio_hvc_clamped_pad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssio_hvc_clamped_pad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssio_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_gpiov2_ff_ff_100C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_gpiov2_ff_ff_n40C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_gpiov2_ss_ss_100C_1v60_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_gpiov2_tt_tt_025C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_hvc_wpad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_hvc_wpad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_hvc_wpad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_hvc_wpad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_ff_100C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_ff_n40C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_ss_100C_1v60_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_tt_025C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_tt_100C_1v80_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_hvc_wpad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_hvc_wpad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_hvc_wpad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_hvc_wpad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_lvc_wpad_ff_100C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_lvc_wpad_ff_n40C_1v95_5v50_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_lvc_wpad_ss_100C_1v60_3v00_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_lvc_wpad_tt_025C_1v80_3v30_3v30.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_xres4v2_ff_ff_100C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_xres4v2_ff_ff_n40C_1v95_5v50.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_xres4v2_ss_ss_100C_1v60_3v00.lib
read_liberty -lib /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_xres4v2_tt_tt_025C_1v80_3v30.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_dir_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_dir_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_dir_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_banks_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_banks_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_banks_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/array_0_0_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/array_0_0_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/array_0_0_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/dataArrayWay_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/dataArrayWay_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/dataArrayWay_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_1_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_1_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_1_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/btb_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/btb_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/btb_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ebtb_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ebtb_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ebtb_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/data_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/data_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/data_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ghist_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ghist_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ghist_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/rob_debug_inst_mem_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/rob_debug_inst_mem_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/rob_debug_inst_mem_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/l2_tlb_ram_0_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/l2_tlb_ram_0_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/l2_tlb_ram_0_ext_tt_025C_1v80.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/mem_ext_ff_n40C_1v95.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/mem_ext_ss_100C_1v60.lib
read_liberty -lib /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/mem_ext_tt_025C_1v80.lib
puts "(hammer) yosys proc"
yosys proc
puts "(hammer) hierarchy -check -top BoomTile"
hierarchy -check -top BoomTile

puts "(hammer) synth -top BoomTile"
synth -top BoomTile

# Optimize the design
puts "(hammer) opt -purge"
opt -purge

# Technology mapping of latches
puts "(hammer) techmap -map /home/ray/conda-sky130/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v"
techmap -map /home/ray/conda-sky130/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v

# Technology mapping of flip-flops
puts "dfflibmap -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib" 
dfflibmap -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
puts "opt" 
opt
# Technology mapping for cells
# ABC supports multiple liberty files, but the hook from Yosys to ABC doesn't
# TODO: this is a bad way of getting one liberty file, need a way to merge all std cell lib files
# NOTE: this breaks for any PDK that has multiple LIB files for std cell library
puts "(hammer) abc -D 20000"
abc -D 20000 \
    -constr "/scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.mapped.sdc" \
    -liberty "/home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib" \
    -showtmp

# Replace undef values with defined constants
# TODO: do we need this??
puts "(hammer) setundef -zero"
setundef -zero

# Split multi-bit nets into single-bit nets.
# Splitting nets resolves unwanted compound assign statements in netlist (assign [..] = [..])
puts "(hammer) splitnets"
splitnets

# Remove unused cells and wires
puts "(hammer) opt_clean -purge"
opt_clean -purge
# Technology mapping of constant hi- and/or lo-drivers
puts "(hammer) hilomap -singleton"
hilomap -singleton \
        -hicell {*}sky130_fd_sc_hd__conb_1 HI \
        -locell {*}sky130_fd_sc_hd__conb_1 LO
# Insert driver cells for pass through wires
puts "(hammer) insbuf -buf {*}sky130_fd_sc_hd__buf_4 A X"
insbuf -buf {*}sky130_fd_sc_hd__buf_4 A X
puts "(hammer) tee -o /scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.synth_check.rpt check"
tee -o /scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.synth_check.rpt check

puts "(hammer) tee -o /scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.synth_stat.txt stat -top BoomTile -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_tt_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_wrapped_tt_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped3_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vdda_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vddio_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssa_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssio_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_gpiov2_tt_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_hvc_wpad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_hvc_wpad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_lvc_wpad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_xres4v2_tt_tt_025C_1v80_3v30.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_dir_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_banks_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/array_0_0_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/dataArrayWay_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_1_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/btb_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ebtb_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/data_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ghist_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/rob_debug_inst_mem_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/l2_tlb_ram_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/mem_ext_tt_025C_1v80.lib"
tee -o /scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.synth_stat.txt stat -top BoomTile -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_tt_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__gpiov2_pad_wrapped_tt_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped3_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vccd_lvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vdda_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vddio_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssa_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped3_pad_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssd_lvc_clamped_pad_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_ef_io__vssio_hvc_clamped_pad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_gpiov2_tt_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_hvc_wpad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_ground_lvc_wpad_tt_025C_1v80_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_hvc_wpad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_power_lvc_wpad_tt_025C_1v80_3v30_3v30.lib -liberty /home/ray/conda-sky130/share/pdk/sky130A/libs.ref/sky130_fd_io/lib/sky130_fd_io__top_xres4v2_tt_tt_025C_1v80_3v30.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_dir_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/cc_banks_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/array_0_0_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/tag_array_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/dataArrayWay_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/table_1_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/btb_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ebtb_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/data_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/meta_0_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/ghist_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/rob_debug_inst_mem_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/l2_tlb_ram_0_ext_tt_025C_1v80.lib -liberty /tmp/hammer_sky130_open_u8pv7r68/cacti_libs/mem_ext_tt_025C_1v80.lib
puts "(hammer) write_verilog -noattr -noexpr -nohex -nodec -defparam \"/scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.mapped.v\""
write_verilog -noattr -noexpr -nohex -nodec -defparam "/scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.mapped.v"

# flatten

# # OpenROAD will throw an error if the verilog from Yosys is not flattened
# # UPDATE ON THIS: nvm, it somehow works now...
# write_verilog -noattr -noexpr -nohex -nodec -defparam "/scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.mapped.v"

# BLIF file seems to be easier to parse than mapped verilog for find_regs functions so leave for now
# write_blif -top BoomTile "/scratch/perf_area_eff/baseline_area_v2/syn_obj/syn-rundir/BoomTile.mapped.blif"
exit