// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomFPUFMAPipe_l4_f64(	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
  input         io_in_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input         io_in_bits_ren3,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input         io_in_bits_swap23,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input  [2:0]  io_in_bits_rm,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input  [1:0]  io_in_bits_fmaCmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input  [64:0] io_in_bits_in1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input  [64:0] io_in_bits_in2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  input  [64:0] io_in_bits_in3,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  output        io_out_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  output [64:0] io_out_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
  output [4:0]  io_out_bits_exc	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
);

  wire [64:0]  _round_io_out;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:343:21]
  wire [4:0]   _round_io_exceptionFlags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:343:21]
  wire         _postmul_io_invalidExc;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire         _postmul_io_rawOut_isNaN;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire         _postmul_io_rawOut_isInf;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire         _postmul_io_rawOut_isZero;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire         _postmul_io_rawOut_sign;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire [12:0]  _postmul_io_rawOut_sExp;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire [55:0]  _postmul_io_rawOut_sig;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  wire [52:0]  _premul_io_mulAddA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire [52:0]  _premul_io_mulAddB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire [105:0] _premul_io_mulAddC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isSigNaNAny;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isNaNAOrB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isInfA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isZeroA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isInfB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isZeroB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_signProd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isNaNC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isInfC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_isZeroC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire [12:0]  _premul_io_toPostMul_sExpSum;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_doSubMags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_CIsDominant;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire [5:0]   _premul_io_toPostMul_CDom_CAlignDist;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire [54:0]  _premul_io_toPostMul_highAlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  wire         _premul_io_toPostMul_bit0AlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  reg          s1_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [52:0]  s1_pipe_b_mulAddA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [52:0]  s1_pipe_b_mulAddB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [105:0] s1_pipe_b_mulAddC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isSigNaNAny;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isNaNAOrB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isInfA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isZeroA;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isInfB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isZeroB;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_signProd;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isNaNC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isInfC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_isZeroC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [12:0]  s1_pipe_b_toPostMul_sExpSum;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_doSubMags;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_CIsDominant;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [5:0]   s1_pipe_b_toPostMul_CDom_CAlignDist;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [54:0]  s1_pipe_b_toPostMul_highAlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s1_pipe_b_toPostMul_bit0AlignedSigC;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [2:0]   s1_pipe_b_rm;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg          s2_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:326:29]
  reg  [106:0] s2_result;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:327:31]
  reg          s2_toPostMul_isSigNaNAny;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isNaNAOrB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isInfA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isZeroA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isInfB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isZeroB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_signProd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isNaNC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isInfC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_isZeroC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg  [12:0]  s2_toPostMul_sExpSum;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_doSubMags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_CIsDominant;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg  [5:0]   s2_toPostMul_CDom_CAlignDist;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg  [54:0]  s2_toPostMul_highAlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg          s2_toPostMul_bit0AlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
  reg  [2:0]   s2_rm;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:329:31]
  reg          s3_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:337:30]
  reg          s3_invalidExc;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:338:32]
  reg          s3_rawOut_isNaN;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
  reg          s3_rawOut_isInf;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
  reg          s3_rawOut_isZero;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
  reg          s3_rawOut_sign;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
  reg  [12:0]  s3_rawOut_sExp;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
  reg  [55:0]  s3_rawOut_sig;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
  reg  [2:0]   s3_rm;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:340:32]
  reg          io_out_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [64:0]  io_out_pipe_b_data;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [4:0]   io_out_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
      s1_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s2_valid <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:326:29]
      s3_valid <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:337:30]
      io_out_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
      s1_pipe_v <= io_in_valid;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s2_valid <= s1_pipe_v;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:326:29, src/main/scala/chisel3/util/Valid.scala:141:24]
      s3_valid <= s2_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:326:29, :337:30]
      io_out_pipe_v <= s3_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:337:30, src/main/scala/chisel3/util/Valid.scala:141:24]
    end
    if (io_in_valid) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:295:14]
      s1_pipe_b_mulAddA <= _premul_io_mulAddA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_mulAddB <= _premul_io_mulAddB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_mulAddC <= _premul_io_mulAddC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isSigNaNAny <= _premul_io_toPostMul_isSigNaNAny;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isNaNAOrB <= _premul_io_toPostMul_isNaNAOrB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isInfA <= _premul_io_toPostMul_isInfA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isZeroA <= _premul_io_toPostMul_isZeroA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isInfB <= _premul_io_toPostMul_isInfB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isZeroB <= _premul_io_toPostMul_isZeroB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_signProd <= _premul_io_toPostMul_signProd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isNaNC <= _premul_io_toPostMul_isNaNC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isInfC <= _premul_io_toPostMul_isInfC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_isZeroC <= _premul_io_toPostMul_isZeroC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_sExpSum <= _premul_io_toPostMul_sExpSum;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_doSubMags <= _premul_io_toPostMul_doSubMags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_CIsDominant <= _premul_io_toPostMul_CIsDominant;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_CDom_CAlignDist <= _premul_io_toPostMul_CDom_CAlignDist;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_highAlignedSigC <= _premul_io_toPostMul_highAlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_toPostMul_bit0AlignedSigC <= _premul_io_toPostMul_bit0AlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_pipe_b_rm <= io_in_bits_rm;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (s1_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s2_result <= {1'h0, {53'h0, s1_pipe_b_mulAddA} * {53'h0, s1_pipe_b_mulAddB}} + {1'h0, s1_pipe_b_mulAddC};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:324:{39,58}, :327:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isSigNaNAny <= s1_pipe_b_toPostMul_isSigNaNAny;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isNaNAOrB <= s1_pipe_b_toPostMul_isNaNAOrB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isInfA <= s1_pipe_b_toPostMul_isInfA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isZeroA <= s1_pipe_b_toPostMul_isZeroA;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isInfB <= s1_pipe_b_toPostMul_isInfB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isZeroB <= s1_pipe_b_toPostMul_isZeroB;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_signProd <= s1_pipe_b_toPostMul_signProd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isNaNC <= s1_pipe_b_toPostMul_isNaNC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isInfC <= s1_pipe_b_toPostMul_isInfC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_isZeroC <= s1_pipe_b_toPostMul_isZeroC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_sExpSum <= s1_pipe_b_toPostMul_sExpSum;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_doSubMags <= s1_pipe_b_toPostMul_doSubMags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_CIsDominant <= s1_pipe_b_toPostMul_CIsDominant;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_CDom_CAlignDist <= s1_pipe_b_toPostMul_CDom_CAlignDist;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_highAlignedSigC <= s1_pipe_b_toPostMul_highAlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_toPostMul_bit0AlignedSigC <= s1_pipe_b_toPostMul_bit0AlignedSigC;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31, src/main/scala/chisel3/util/Valid.scala:142:26]
      s2_rm <= s1_pipe_b_rm;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:329:31, src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (s2_valid) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:326:29]
      s3_invalidExc <= _postmul_io_invalidExc;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :338:32]
      s3_rawOut_isNaN <= _postmul_io_rawOut_isNaN;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :339:32]
      s3_rawOut_isInf <= _postmul_io_rawOut_isInf;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :339:32]
      s3_rawOut_isZero <= _postmul_io_rawOut_isZero;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :339:32]
      s3_rawOut_sign <= _postmul_io_rawOut_sign;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :339:32]
      s3_rawOut_sExp <= _postmul_io_rawOut_sExp;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :339:32]
      s3_rawOut_sig <= _postmul_io_rawOut_sig;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23, :339:32]
      s3_rm <= s2_rm;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:329:31, :340:32]
    end
    if (s3_valid) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:337:30]
      io_out_pipe_b_data <= ({65{_round_io_out[63:61] != 3'h7}} | 65'h1EFEFFFFFFFFFFFFF) & _round_io_out;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:343:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :414:10, src/main/scala/chisel3/util/Valid.scala:142:26]
      io_out_pipe_b_exc <= _round_io_exceptionFlags;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:343:21, src/main/scala/chisel3/util/Valid.scala:142:26]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:20];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
        for (logic [4:0] i = 5'h0; i < 5'h15; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
        end	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
        s1_pipe_v = _RANDOM[5'h0][0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:141:24]
        s1_pipe_b_mulAddA = {_RANDOM[5'h0][31:1], _RANDOM[5'h1][21:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        s1_pipe_b_mulAddB = {_RANDOM[5'h1][31:22], _RANDOM[5'h2], _RANDOM[5'h3][10:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_mulAddC = {_RANDOM[5'h3][31:11], _RANDOM[5'h4], _RANDOM[5'h5], _RANDOM[5'h6][20:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isSigNaNAny = _RANDOM[5'h6][21];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isNaNAOrB = _RANDOM[5'h6][22];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isInfA = _RANDOM[5'h6][23];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isZeroA = _RANDOM[5'h6][24];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isInfB = _RANDOM[5'h6][25];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isZeroB = _RANDOM[5'h6][26];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_signProd = _RANDOM[5'h6][27];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isNaNC = _RANDOM[5'h6][28];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isInfC = _RANDOM[5'h6][29];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_isZeroC = _RANDOM[5'h6][30];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_sExpSum = {_RANDOM[5'h6][31], _RANDOM[5'h7][11:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_doSubMags = _RANDOM[5'h7][12];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_CIsDominant = _RANDOM[5'h7][13];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_CDom_CAlignDist = _RANDOM[5'h7][19:14];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_highAlignedSigC = {_RANDOM[5'h7][31:20], _RANDOM[5'h8], _RANDOM[5'h9][10:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_toPostMul_bit0AlignedSigC = _RANDOM[5'h9][11];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_pipe_b_rm = _RANDOM[5'h9][14:12];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_valid = _RANDOM[5'h9][15];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :326:29, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_result = {_RANDOM[5'h9][31:16], _RANDOM[5'hA], _RANDOM[5'hB], _RANDOM[5'hC][26:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :327:31, src/main/scala/chisel3/util/Valid.scala:142:26]
        s2_toPostMul_isSigNaNAny = _RANDOM[5'hC][27];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :327:31, :328:31]
        s2_toPostMul_isNaNAOrB = _RANDOM[5'hC][28];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :327:31, :328:31]
        s2_toPostMul_isInfA = _RANDOM[5'hC][29];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :327:31, :328:31]
        s2_toPostMul_isZeroA = _RANDOM[5'hC][30];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :327:31, :328:31]
        s2_toPostMul_isInfB = _RANDOM[5'hC][31];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :327:31, :328:31]
        s2_toPostMul_isZeroB = _RANDOM[5'hD][0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_signProd = _RANDOM[5'hD][1];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_isNaNC = _RANDOM[5'hD][2];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_isInfC = _RANDOM[5'hD][3];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_isZeroC = _RANDOM[5'hD][4];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_sExpSum = _RANDOM[5'hD][17:5];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_doSubMags = _RANDOM[5'hD][18];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_CIsDominant = _RANDOM[5'hD][19];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_CDom_CAlignDist = _RANDOM[5'hD][25:20];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_highAlignedSigC = {_RANDOM[5'hD][31:26], _RANDOM[5'hE], _RANDOM[5'hF][16:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_toPostMul_bit0AlignedSigC = _RANDOM[5'hF][17];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31]
        s2_rm = _RANDOM[5'hF][20:18];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :329:31]
        s3_valid = _RANDOM[5'hF][21];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :337:30]
        s3_invalidExc = _RANDOM[5'hF][22];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :338:32]
        s3_rawOut_isNaN = _RANDOM[5'hF][23];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :339:32]
        s3_rawOut_isInf = _RANDOM[5'hF][24];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :339:32]
        s3_rawOut_isZero = _RANDOM[5'hF][25];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :339:32]
        s3_rawOut_sign = _RANDOM[5'hF][26];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :339:32]
        s3_rawOut_sExp = {_RANDOM[5'hF][31:27], _RANDOM[5'h10][7:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :328:31, :339:32]
        s3_rawOut_sig = {_RANDOM[5'h10][31:8], _RANDOM[5'h11]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :339:32]
        s3_rm = _RANDOM[5'h12][2:0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :340:32]
        io_out_pipe_v = _RANDOM[5'h12][3];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :340:32, src/main/scala/chisel3/util/Valid.scala:141:24]
        io_out_pipe_b_data = {_RANDOM[5'h12][31:4], _RANDOM[5'h13], _RANDOM[5'h14][4:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, :340:32, src/main/scala/chisel3/util/Valid.scala:142:26]
        io_out_pipe_b_exc = _RANDOM[5'h14][9:5];	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MulAddRecFNToRaw_preMul_e11_s53 premul (	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
    .io_op                        (io_in_bits_fmaCmd),
    .io_a                         (io_in_bits_in1),
    .io_b                         (io_in_bits_swap23 ? 65'h8000000000000000 : io_in_bits_in2),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:311:22]
    .io_c                         (io_in_bits_ren3 | io_in_bits_swap23 ? io_in_bits_in3 : (io_in_bits_in1 ^ io_in_bits_in2) & 65'h10000000000000000),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:304:{36,54}, :312:{22,31}]
    .io_mulAddA                   (_premul_io_mulAddA),
    .io_mulAddB                   (_premul_io_mulAddB),
    .io_mulAddC                   (_premul_io_mulAddC),
    .io_toPostMul_isSigNaNAny     (_premul_io_toPostMul_isSigNaNAny),
    .io_toPostMul_isNaNAOrB       (_premul_io_toPostMul_isNaNAOrB),
    .io_toPostMul_isInfA          (_premul_io_toPostMul_isInfA),
    .io_toPostMul_isZeroA         (_premul_io_toPostMul_isZeroA),
    .io_toPostMul_isInfB          (_premul_io_toPostMul_isInfB),
    .io_toPostMul_isZeroB         (_premul_io_toPostMul_isZeroB),
    .io_toPostMul_signProd        (_premul_io_toPostMul_signProd),
    .io_toPostMul_isNaNC          (_premul_io_toPostMul_isNaNC),
    .io_toPostMul_isInfC          (_premul_io_toPostMul_isInfC),
    .io_toPostMul_isZeroC         (_premul_io_toPostMul_isZeroC),
    .io_toPostMul_sExpSum         (_premul_io_toPostMul_sExpSum),
    .io_toPostMul_doSubMags       (_premul_io_toPostMul_doSubMags),
    .io_toPostMul_CIsDominant     (_premul_io_toPostMul_CIsDominant),
    .io_toPostMul_CDom_CAlignDist (_premul_io_toPostMul_CDom_CAlignDist),
    .io_toPostMul_highAlignedSigC (_premul_io_toPostMul_highAlignedSigC),
    .io_toPostMul_bit0AlignedSigC (_premul_io_toPostMul_bit0AlignedSigC)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:308:22]
  MulAddRecFNToRaw_postMul_e11_s53 postmul (	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
    .io_fromPreMul_isSigNaNAny     (s2_toPostMul_isSigNaNAny),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isNaNAOrB       (s2_toPostMul_isNaNAOrB),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isInfA          (s2_toPostMul_isInfA),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isZeroA         (s2_toPostMul_isZeroA),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isInfB          (s2_toPostMul_isInfB),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isZeroB         (s2_toPostMul_isZeroB),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_signProd        (s2_toPostMul_signProd),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isNaNC          (s2_toPostMul_isNaNC),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isInfC          (s2_toPostMul_isInfC),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_isZeroC         (s2_toPostMul_isZeroC),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_sExpSum         (s2_toPostMul_sExpSum),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_doSubMags       (s2_toPostMul_doSubMags),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_CIsDominant     (s2_toPostMul_CIsDominant),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_CDom_CAlignDist (s2_toPostMul_CDom_CAlignDist),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_highAlignedSigC (s2_toPostMul_highAlignedSigC),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_fromPreMul_bit0AlignedSigC (s2_toPostMul_bit0AlignedSigC),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:328:31]
    .io_mulAddResult               (s2_result),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:327:31]
    .io_roundingMode               (s2_rm),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:329:31]
    .io_invalidExc                 (_postmul_io_invalidExc),
    .io_rawOut_isNaN               (_postmul_io_rawOut_isNaN),
    .io_rawOut_isInf               (_postmul_io_rawOut_isInf),
    .io_rawOut_isZero              (_postmul_io_rawOut_isZero),
    .io_rawOut_sign                (_postmul_io_rawOut_sign),
    .io_rawOut_sExp                (_postmul_io_rawOut_sExp),
    .io_rawOut_sig                 (_postmul_io_rawOut_sig)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:332:23]
  RoundRawFNToRecFN_e11_s53 round (	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:343:21]
    .io_invalidExc     (s3_invalidExc),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:338:32]
    .io_infiniteExc    (1'h0),
    .io_in_isNaN       (s3_rawOut_isNaN),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
    .io_in_isInf       (s3_rawOut_isInf),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
    .io_in_isZero      (s3_rawOut_isZero),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
    .io_in_sign        (s3_rawOut_sign),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
    .io_in_sExp        (s3_rawOut_sExp),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
    .io_in_sig         (s3_rawOut_sig),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:339:32]
    .io_roundingMode   (s3_rm),	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:340:32]
    .io_out            (_round_io_out),
    .io_exceptionFlags (_round_io_exceptionFlags)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:343:21]
  assign io_out_valid = io_out_pipe_v;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:141:24]
  assign io_out_bits_data = io_out_pipe_b_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
  assign io_out_bits_exc = io_out_pipe_b_exc;	// @[generators/boom/src/main/scala/v3/exu/execution-units/fpu.scala:289:7, src/main/scala/chisel3/util/Valid.scala:142:26]
endmodule

