// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BranchKillableQueue_4(	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
  output        io_enq_ready,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_valid,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [31:0] io_enq_bits_uop_inst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [31:0] io_enq_bits_uop_debug_inst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_rvc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [39:0] io_enq_bits_uop_debug_pc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_uop_iq_type,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [9:0]  io_enq_bits_uop_fu_code,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_uop_ctrl_br_type,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_ctrl_op1_sel,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_uop_ctrl_op2_sel,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_uop_ctrl_imm_sel,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_uop_ctrl_csr_cmd,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_iw_state,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_iw_p1_poisoned,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_iw_p2_poisoned,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_br,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_jalr,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_jal,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_sfb,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [11:0] io_enq_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_uop_br_tag,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_uop_ftq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_edge_inst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_uop_pc_lob,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_taken,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [19:0] io_enq_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [11:0] io_enq_bits_uop_csr_addr,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_rxq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_uop_prs1,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_uop_prs2,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_uop_prs3,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_uop_ppred,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_prs1_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_prs2_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_prs3_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ppred_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_uop_stale_pdst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_exception,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [63:0] io_enq_bits_uop_exc_cause,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_bypassable,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_fence,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_fencei,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_sys_pc2epc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_is_unique,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_flush_on_commit,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ldst_is_rs1,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_uop_ldst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_uop_lrs1,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_uop_lrs2,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_uop_lrs3,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_ldst_val,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_frs3_en,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_fp_single,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_xcpt_pf_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_xcpt_ae_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_xcpt_ma_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_bp_debug_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_uop_bp_xcpt_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_debug_fsrc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_uop_debug_tsrc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [64:0] io_enq_bits_data,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_valid,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_fflags_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [31:0] io_enq_bits_fflags_bits_uop_inst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [31:0] io_enq_bits_fflags_bits_uop_debug_inst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_rvc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [39:0] io_enq_bits_fflags_bits_uop_debug_pc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_fflags_bits_uop_iq_type,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [9:0]  io_enq_bits_fflags_bits_uop_fu_code,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_fflags_bits_uop_ctrl_br_type,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_ctrl_op1_sel,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_fflags_bits_uop_ctrl_op2_sel,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_fflags_bits_uop_ctrl_imm_sel,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_fflags_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [2:0]  io_enq_bits_fflags_bits_uop_ctrl_csr_cmd,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_iw_state,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_iw_p1_poisoned,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_iw_p2_poisoned,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_br,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_jalr,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_jal,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_sfb,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [11:0] io_enq_bits_fflags_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_fflags_bits_uop_br_tag,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_fflags_bits_uop_ftq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_edge_inst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_fflags_bits_uop_pc_lob,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_taken,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [19:0] io_enq_bits_fflags_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [11:0] io_enq_bits_fflags_bits_uop_csr_addr,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_fflags_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_fflags_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [3:0]  io_enq_bits_fflags_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_rxq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_fflags_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_fflags_bits_uop_prs1,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_fflags_bits_uop_prs2,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_fflags_bits_uop_prs3,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_fflags_bits_uop_ppred,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_prs1_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_prs2_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_prs3_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ppred_busy,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [6:0]  io_enq_bits_fflags_bits_uop_stale_pdst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_exception,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [63:0] io_enq_bits_fflags_bits_uop_exc_cause,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_bypassable,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_fflags_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_fence,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_fencei,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_sys_pc2epc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_is_unique,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_flush_on_commit,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ldst_is_rs1,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_fflags_bits_uop_ldst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_fflags_bits_uop_lrs1,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_fflags_bits_uop_lrs2,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [5:0]  io_enq_bits_fflags_bits_uop_lrs3,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_ldst_val,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_frs3_en,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_fp_single,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_xcpt_pf_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_xcpt_ae_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_xcpt_ma_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_bp_debug_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_enq_bits_fflags_bits_uop_bp_xcpt_if,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_debug_fsrc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [1:0]  io_enq_bits_fflags_bits_uop_debug_tsrc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [4:0]  io_enq_bits_fflags_bits_flags,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_deq_ready,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_deq_valid,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [6:0]  io_deq_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [11:0] io_deq_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [5:0]  io_deq_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [3:0]  io_deq_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [6:0]  io_deq_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_deq_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_deq_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [1:0]  io_deq_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_deq_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [64:0] io_deq_bits_data,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_deq_bits_predicated,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_deq_bits_fflags_valid,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [5:0]  io_deq_bits_fflags_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output [4:0]  io_deq_bits_fflags_bits_flags,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [11:0] io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input  [11:0] io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  input         io_flush,	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
  output        io_empty	// @[generators/boom/src/main/scala/v3/util/util.scala:453:14]
);

  wire [77:0] _ram_ext_R0_data;	// @[generators/boom/src/main/scala/v3/util/util.scala:464:20]
  reg         valids_0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_1;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_2;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_3;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_4;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_5;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_6;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg         valids_7;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
  reg  [6:0]  uops_0_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_0_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_0_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_0_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_0_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_0_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_0_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_0_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_1_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_1_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_1_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_1_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_1_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_1_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_1_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_1_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_1_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_2_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_2_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_2_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_2_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_2_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_2_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_2_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_2_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_2_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_3_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_3_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_3_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_3_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_3_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_3_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_3_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_3_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_3_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_4_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_4_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_4_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_4_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_4_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_4_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_4_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_4_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_4_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_5_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_5_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_5_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_5_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_5_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_5_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_5_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_5_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_5_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_6_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_6_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_6_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_6_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_6_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_6_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_6_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_6_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_6_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_7_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [11:0] uops_7_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [5:0]  uops_7_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [3:0]  uops_7_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [6:0]  uops_7_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_7_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_7_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [1:0]  uops_7_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg         uops_7_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
  reg  [2:0]  enq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg  [2:0]  deq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         maybe_full;	// @[generators/boom/src/main/scala/v3/util/util.scala:470:27]
  wire        ptr_match = enq_ptr_value == deq_ptr_value;	// @[generators/boom/src/main/scala/v3/util/util.scala:472:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        io_empty_0 = ptr_match & ~maybe_full;	// @[generators/boom/src/main/scala/v3/util/util.scala:470:27, :472:33, :473:{25,28}]
  wire        full = ptr_match & maybe_full;	// @[generators/boom/src/main/scala/v3/util/util.scala:470:27, :472:33, :474:24]
  reg         casez_tmp;	// @[generators/boom/src/main/scala/v3/util/util.scala:476:42]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:476:42]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:476:42, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp = valids_0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      3'b001:
        casez_tmp = valids_1;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      3'b010:
        casez_tmp = valids_2;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      3'b011:
        casez_tmp = valids_3;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      3'b100:
        casez_tmp = valids_4;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      3'b101:
        casez_tmp = valids_5;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      3'b110:
        casez_tmp = valids_6;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
      default:
        casez_tmp = valids_7;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24, :476:42]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:476:42, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [6:0]  casez_tmp_0;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_0 = uops_0_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_0 = uops_1_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_0 = uops_2_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_0 = uops_3_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_0 = uops_4_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_0 = uops_5_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_0 = uops_6_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_0 = uops_7_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [11:0] casez_tmp_1;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_1 = uops_0_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_1 = uops_1_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_1 = uops_2_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_1 = uops_3_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_1 = uops_4_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_1 = uops_5_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_1 = uops_6_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_1 = uops_7_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [5:0]  casez_tmp_2;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_2 = uops_0_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_2 = uops_1_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_2 = uops_2_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_2 = uops_3_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_2 = uops_4_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_2 = uops_5_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_2 = uops_6_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_2 = uops_7_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [3:0]  casez_tmp_3;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_3 = uops_0_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_3 = uops_1_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_3 = uops_2_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_3 = uops_3_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_3 = uops_4_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_3 = uops_5_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_3 = uops_6_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_3 = uops_7_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [6:0]  casez_tmp_4;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_4 = uops_0_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_4 = uops_1_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_4 = uops_2_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_4 = uops_3_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_4 = uops_4_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_4 = uops_5_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_4 = uops_6_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_4 = uops_7_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_5;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_5 = uops_0_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_5 = uops_1_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_5 = uops_2_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_5 = uops_3_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_5 = uops_4_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_5 = uops_5_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_5 = uops_6_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_5 = uops_7_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_6;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_6 = uops_0_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_6 = uops_1_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_6 = uops_2_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_6 = uops_3_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_6 = uops_4_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_6 = uops_5_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_6 = uops_6_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_6 = uops_7_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [1:0]  casez_tmp_7;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_7 = uops_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_7 = uops_1_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_7 = uops_2_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_7 = uops_3_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_7 = uops_4_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_7 = uops_5_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_7 = uops_6_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_7 = uops_7_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_8;	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
  always @(*) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      3'b000:
        casez_tmp_8 = uops_0_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b001:
        casez_tmp_8 = uops_1_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b010:
        casez_tmp_8 = uops_2_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b011:
        casez_tmp_8 = uops_3_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b100:
        casez_tmp_8 = uops_4_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b101:
        casez_tmp_8 = uops_5_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      3'b110:
        casez_tmp_8 = uops_6_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
      default:
        casez_tmp_8 = uops_7_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20, :508:19]
    endcase	// @[generators/boom/src/main/scala/v3/util/util.scala:508:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  wire        do_deq = ~io_empty_0 & (io_deq_ready | ~casez_tmp) & ~io_empty_0;	// @[generators/boom/src/main/scala/v3/util/util.scala:473:25, :476:{24,39,42,66,69}, :510:27, :515:21, :517:19, :520:14]
  wire        do_enq = ~(io_empty_0 & io_deq_ready) & ~full & io_enq_valid;	// @[generators/boom/src/main/scala/v3/util/util.scala:473:25, :474:24, :475:24, :504:19, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN = enq_ptr_value == 3'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_0 = do_enq & _GEN;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_1 = enq_ptr_value == 3'h1;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_2 = do_enq & _GEN_1;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_3 = enq_ptr_value == 3'h2;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_4 = do_enq & _GEN_3;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_5 = enq_ptr_value == 3'h3;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_6 = do_enq & _GEN_5;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_7 = enq_ptr_value == 3'h4;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_8 = do_enq & _GEN_7;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_9 = enq_ptr_value == 3'h5;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_10 = do_enq & _GEN_9;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_11 = enq_ptr_value == 3'h6;	// @[generators/boom/src/main/scala/v3/util/util.scala:489:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_12 = do_enq & _GEN_11;	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_13 = do_enq & (&enq_ptr_value);	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :481:16, :487:17, :489:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [11:0] _uops_br_mask_T_1 = io_enq_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:{25,27}]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
      valids_0 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_1 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_2 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_3 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_4 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_5 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_6 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      valids_7 <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:465:24]
      enq_ptr_value <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      deq_ptr_value <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      maybe_full <= 1'h0;	// @[generators/boom/src/main/scala/v3/util/util.scala:470:27]
    end
    else begin	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
      valids_0 <= ~(do_deq & deq_ptr_value == 3'h0) & (_GEN_0 | valids_0 & (io_brupdate_b1_mispredict_mask & uops_0_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_1 <= ~(do_deq & deq_ptr_value == 3'h1) & (_GEN_2 | valids_1 & (io_brupdate_b1_mispredict_mask & uops_1_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_2 <= ~(do_deq & deq_ptr_value == 3'h2) & (_GEN_4 | valids_2 & (io_brupdate_b1_mispredict_mask & uops_2_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_3 <= ~(do_deq & deq_ptr_value == 3'h3) & (_GEN_6 | valids_3 & (io_brupdate_b1_mispredict_mask & uops_3_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_4 <= ~(do_deq & deq_ptr_value == 3'h4) & (_GEN_8 | valids_4 & (io_brupdate_b1_mispredict_mask & uops_4_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_5 <= ~(do_deq & deq_ptr_value == 3'h5) & (_GEN_10 | valids_5 & (io_brupdate_b1_mispredict_mask & uops_5_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_6 <= ~(do_deq & deq_ptr_value == 3'h6) & (_GEN_12 | valids_6 & (io_brupdate_b1_mispredict_mask & uops_6_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_7 <= ~(do_deq & (&deq_ptr_value)) & (_GEN_13 | valids_7 & (io_brupdate_b1_mispredict_mask & uops_7_br_mask) == 12'h0 & ~io_flush);	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :465:24, :466:20, :476:{24,66}, :481:{16,29,69,72}, :487:17, :489:33, :495:17, :496:27, :515:21, :520:14, src/main/scala/chisel3/util/Counter.scala:61:40]
      if (do_enq)	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        enq_ptr_value <= enq_ptr_value + 3'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (do_deq)	// @[generators/boom/src/main/scala/v3/util/util.scala:476:{24,66}, :515:21, :520:14]
        deq_ptr_value <= deq_ptr_value + 3'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (~(do_enq == do_deq))	// @[generators/boom/src/main/scala/v3/util/util.scala:470:27, :475:24, :476:{24,66}, :500:{16,28}, :501:16, :515:21, :520:14, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        maybe_full <= do_enq;	// @[generators/boom/src/main/scala/v3/util/util.scala:470:27, :475:24, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    if (_GEN_0) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_0_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_0_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_0_br_mask <= do_enq & _GEN ? _uops_br_mask_T_1 : ({12{~valids_0}} | ~io_brupdate_b1_resolve_mask) & uops_0_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_2) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_1_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_1_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_1_br_mask <= do_enq & _GEN_1 ? _uops_br_mask_T_1 : ({12{~valids_1}} | ~io_brupdate_b1_resolve_mask) & uops_1_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_4) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_2_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_2_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_2_br_mask <= do_enq & _GEN_3 ? _uops_br_mask_T_1 : ({12{~valids_2}} | ~io_brupdate_b1_resolve_mask) & uops_2_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_6) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_3_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_3_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_3_br_mask <= do_enq & _GEN_5 ? _uops_br_mask_T_1 : ({12{~valids_3}} | ~io_brupdate_b1_resolve_mask) & uops_3_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_4_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_4_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_4_br_mask <= do_enq & _GEN_7 ? _uops_br_mask_T_1 : ({12{~valids_4}} | ~io_brupdate_b1_resolve_mask) & uops_4_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_10) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_5_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_5_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_5_br_mask <= do_enq & _GEN_9 ? _uops_br_mask_T_1 : ({12{~valids_5}} | ~io_brupdate_b1_resolve_mask) & uops_5_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_12) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_6_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_6_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_6_br_mask <= do_enq & _GEN_11 ? _uops_br_mask_T_1 : ({12{~valids_6}} | ~io_brupdate_b1_resolve_mask) & uops_6_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN_13) begin	// @[generators/boom/src/main/scala/v3/util/util.scala:481:16, :487:17, :489:33]
      uops_7_uopc <= io_enq_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_pdst <= io_enq_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_dst_rtype <= io_enq_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
      uops_7_fp_val <= io_enq_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/util/util.scala:466:20]
    end
    uops_7_br_mask <= do_enq & (&enq_ptr_value) ? _uops_br_mask_T_1 : ({12{~valids_7}} | ~io_brupdate_b1_resolve_mask) & uops_7_br_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:25, :89:23, :465:24, :466:20, :475:24, :482:22, :483:23, :487:17, :489:33, :491:33, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:101];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
    initial begin	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
        for (logic [6:0] i = 7'h0; i < 7'h66; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
        end	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
        valids_0 = _RANDOM[7'h0][0];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_1 = _RANDOM[7'h0][1];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_2 = _RANDOM[7'h0][2];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_3 = _RANDOM[7'h0][3];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_4 = _RANDOM[7'h0][4];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_5 = _RANDOM[7'h0][5];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_6 = _RANDOM[7'h0][6];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        valids_7 = _RANDOM[7'h0][7];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24]
        uops_0_uopc = _RANDOM[7'h0][14:8];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :465:24, :466:20]
        uops_0_br_mask = _RANDOM[7'h5][16:5];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_rob_idx = _RANDOM[7'h7][7:2];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_stq_idx = _RANDOM[7'h7][15:12];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_pdst = _RANDOM[7'h7][24:18];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_is_amo = _RANDOM[7'hB][10];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_uses_stq = _RANDOM[7'hB][12];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_dst_rtype = _RANDOM[7'hC][11:10];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_0_fp_val = _RANDOM[7'hC][17];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_uopc = {_RANDOM[7'hC][31:28], _RANDOM[7'hD][2:0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_br_mask = {_RANDOM[7'h11][31:25], _RANDOM[7'h12][4:0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_rob_idx = _RANDOM[7'h13][27:22];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_stq_idx = _RANDOM[7'h14][3:0];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_pdst = _RANDOM[7'h14][12:6];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_is_amo = _RANDOM[7'h17][30];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_uses_stq = _RANDOM[7'h18][0];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_dst_rtype = _RANDOM[7'h18][31:30];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_1_fp_val = _RANDOM[7'h19][5];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_uopc = _RANDOM[7'h19][22:16];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_br_mask = _RANDOM[7'h1E][24:13];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_rob_idx = _RANDOM[7'h20][15:10];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_stq_idx = _RANDOM[7'h20][23:20];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_pdst = {_RANDOM[7'h20][31:26], _RANDOM[7'h21][0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_is_amo = _RANDOM[7'h24][18];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_uses_stq = _RANDOM[7'h24][20];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_dst_rtype = _RANDOM[7'h25][19:18];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_2_fp_val = _RANDOM[7'h25][25];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_uopc = _RANDOM[7'h26][10:4];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_br_mask = _RANDOM[7'h2B][12:1];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_rob_idx = {_RANDOM[7'h2C][31:30], _RANDOM[7'h2D][3:0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_stq_idx = _RANDOM[7'h2D][11:8];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_pdst = _RANDOM[7'h2D][20:14];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_is_amo = _RANDOM[7'h31][6];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_uses_stq = _RANDOM[7'h31][8];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_dst_rtype = _RANDOM[7'h32][7:6];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_3_fp_val = _RANDOM[7'h32][13];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_uopc = _RANDOM[7'h32][30:24];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_br_mask = {_RANDOM[7'h37][31:21], _RANDOM[7'h38][0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_rob_idx = _RANDOM[7'h39][23:18];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_stq_idx = _RANDOM[7'h39][31:28];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_pdst = _RANDOM[7'h3A][8:2];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_is_amo = _RANDOM[7'h3D][26];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_uses_stq = _RANDOM[7'h3D][28];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_dst_rtype = _RANDOM[7'h3E][27:26];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_4_fp_val = _RANDOM[7'h3F][1];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_uopc = _RANDOM[7'h3F][18:12];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_br_mask = _RANDOM[7'h44][20:9];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_rob_idx = _RANDOM[7'h46][11:6];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_stq_idx = _RANDOM[7'h46][19:16];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_pdst = _RANDOM[7'h46][28:22];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_is_amo = _RANDOM[7'h4A][14];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_uses_stq = _RANDOM[7'h4A][16];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_dst_rtype = _RANDOM[7'h4B][15:14];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_5_fp_val = _RANDOM[7'h4B][21];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_uopc = _RANDOM[7'h4C][6:0];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_br_mask = {_RANDOM[7'h50][31:29], _RANDOM[7'h51][8:0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_rob_idx = _RANDOM[7'h52][31:26];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_stq_idx = _RANDOM[7'h53][7:4];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_pdst = _RANDOM[7'h53][16:10];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_is_amo = _RANDOM[7'h57][2];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_uses_stq = _RANDOM[7'h57][4];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_dst_rtype = _RANDOM[7'h58][3:2];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_6_fp_val = _RANDOM[7'h58][9];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_uopc = _RANDOM[7'h58][26:20];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_br_mask = _RANDOM[7'h5D][28:17];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_rob_idx = _RANDOM[7'h5F][19:14];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_stq_idx = _RANDOM[7'h5F][27:24];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_pdst = {_RANDOM[7'h5F][31:30], _RANDOM[7'h60][4:0]};	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_is_amo = _RANDOM[7'h63][22];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_uses_stq = _RANDOM[7'h63][24];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_dst_rtype = _RANDOM[7'h64][23:22];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        uops_7_fp_val = _RANDOM[7'h64][29];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :466:20]
        enq_ptr_value = _RANDOM[7'h65][10:8];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, src/main/scala/chisel3/util/Counter.scala:61:40]
        deq_ptr_value = _RANDOM[7'h65][13:11];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, src/main/scala/chisel3/util/Counter.scala:61:40]
        maybe_full = _RANDOM[7'h65][14];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :470:27, src/main/scala/chisel3/util/Counter.scala:61:40]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_8x78 ram_ext (	// @[generators/boom/src/main/scala/v3/util/util.scala:464:20]
    .R0_addr (deq_ptr_value),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .W0_en   (do_enq),	// @[generators/boom/src/main/scala/v3/util/util.scala:475:24, :515:21, :521:{27,36}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_fflags_bits_flags, io_enq_bits_fflags_bits_uop_rob_idx, io_enq_bits_fflags_valid, 1'h0, io_enq_bits_data})	// @[generators/boom/src/main/scala/v3/util/util.scala:464:20]
  );	// @[generators/boom/src/main/scala/v3/util/util.scala:464:20]
  assign io_enq_ready = ~full;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :474:24, :504:19]
  assign io_deq_valid = io_empty_0 ? io_enq_valid : ~io_empty_0 & casez_tmp & (io_brupdate_b1_mispredict_mask & casez_tmp_1) == 12'h0 & ~io_flush;	// @[generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}, :448:7, :473:25, :476:{42,69}, :508:19, :509:{27,40,65,108,111}, :515:21, :516:20]
  assign io_deq_bits_uop_uopc = io_empty_0 ? io_enq_bits_uop_uopc : casez_tmp_0;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_br_mask = io_empty_0 ? io_enq_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask : casez_tmp_1 & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/util/util.scala:85:{25,27}, :448:7, :473:25, :508:19, :511:27, :515:21, :518:31]
  assign io_deq_bits_uop_rob_idx = io_empty_0 ? io_enq_bits_uop_rob_idx : casez_tmp_2;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_stq_idx = io_empty_0 ? io_enq_bits_uop_stq_idx : casez_tmp_3;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_pdst = io_empty_0 ? io_enq_bits_uop_pdst : casez_tmp_4;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_is_amo = io_empty_0 ? io_enq_bits_uop_is_amo : casez_tmp_5;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_uses_stq = io_empty_0 ? io_enq_bits_uop_uses_stq : casez_tmp_6;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_dst_rtype = io_empty_0 ? io_enq_bits_uop_dst_rtype : casez_tmp_7;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_uop_fp_val = io_empty_0 ? io_enq_bits_uop_fp_val : casez_tmp_8;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25, :508:19, :510:27, :515:21, :517:19]
  assign io_deq_bits_data = io_empty_0 ? io_enq_bits_data : _ram_ext_R0_data[64:0];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :464:20, :473:25, :510:27, :515:21, :517:19]
  assign io_deq_bits_predicated = ~io_empty_0 & _ram_ext_R0_data[65];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :464:20, :473:25, :510:27, :515:21, :517:19]
  assign io_deq_bits_fflags_valid = io_empty_0 ? io_enq_bits_fflags_valid : _ram_ext_R0_data[66];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :464:20, :473:25, :510:27, :515:21, :517:19]
  assign io_deq_bits_fflags_bits_uop_rob_idx = io_empty_0 ? io_enq_bits_fflags_bits_uop_rob_idx : _ram_ext_R0_data[72:67];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :464:20, :473:25, :510:27, :515:21, :517:19]
  assign io_deq_bits_fflags_bits_flags = io_empty_0 ? io_enq_bits_fflags_bits_flags : _ram_ext_R0_data[77:73];	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :464:20, :473:25, :510:27, :515:21, :517:19]
  assign io_empty = io_empty_0;	// @[generators/boom/src/main/scala/v3/util/util.scala:448:7, :473:25]
endmodule

