// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module MemAddrCalcUnit(	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [7:0]  io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [5:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [3:0]  io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [3:0]  io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [4:0]  io_req_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [1:0]  io_req_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_is_fence,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [64:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [64:0] io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [7:0]  io_resp_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [5:0]  io_resp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [3:0]  io_resp_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [3:0]  io_resp_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [6:0]  io_resp_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [4:0]  io_resp_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [1:0]  io_resp_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_is_fence,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [64:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [39:0] io_resp_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_mxcpt_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_sfence_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_sfence_bits_rs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_sfence_bits_rs2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  output [38:0] io_resp_bits_sfence_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [7:0]  io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
  input  [7:0]  io_brupdate_b1_mispredict_mask	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:168:14]
);

  wire [63:0] _sum_T_3 = io_req_bits_rs1_data[63:0] + {{52{io_req_bits_uop_imm_packed[19]}}, io_req_bits_uop_imm_packed[19:8]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:493:{42,70}]
  wire        misaligned = io_req_bits_uop_mem_size == 2'h1 & _sum_T_3[0] | io_req_bits_uop_mem_size == 2'h2 & (|(_sum_T_3[1:0])) | (&io_req_bits_uop_mem_size) & (|(_sum_T_3[2:0]));	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:493:42, :518:{11,19,40,54}, :519:{11,19,40,46,56}, :520:{11,19,40,46}]
  wire        ma_ld = io_req_valid & io_req_bits_uop_uopc == 7'h1 & misaligned;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:518:54, :519:56, :530:{29,53,63}]
  wire        ma_st = io_req_valid & (io_req_bits_uop_uopc == 7'h2 | io_req_bits_uop_uopc == 7'h43) & misaligned;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:518:54, :519:56, :531:{29,54,65,89,104}]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12]
    wire _GEN = io_req_valid & io_req_bits_uop_ctrl_is_std;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:28]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12]
      if (~reset & _GEN & io_req_bits_rs2_data[64]) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:{12,28,59}, :505:24]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12]
          $error("Assertion failed: 65th bit set in MemAddrCalcUnit.\n    at functional-unit.scala:504 assert (!(io.req.valid && io.req.bits.uop.ctrl.is_std &&\n");	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12]
      end
      if (~reset & _GEN & io_req_bits_uop_fp_val) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:{12,28}, :507:{12,59}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:507:12]
          $error("Assertion failed: FP store-data should now be going through a different unit.\n    at functional-unit.scala:507 assert (!(io.req.valid && io.req.bits.uop.ctrl.is_std && io.req.bits.uop.fp_val),\n");	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:507:12]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:507:12]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:507:12]
      end
      if (~reset & io_req_bits_uop_fp_val & io_req_valid & io_req_bits_uop_uopc != 7'h1 & io_req_bits_uop_uopc != 7'h2) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12, :511:{10,36,52,76}, :512:{17,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:511:10]
          $error("Assertion failed: [maddrcalc] assert we never get store data in here.\n    at functional-unit.scala:511 assert (!(io.req.bits.uop.fp_val && io.req.valid && io.req.bits.uop.uopc =/=\n");	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:511:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:511:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:511:10]
      end
      if (~reset & ma_ld & ma_st) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:504:12, :530:{29,63}, :531:{29,104}, :547:{10,19}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:547:10]
          $error("Assertion failed: Mutually-exclusive exceptions are firing.\n    at functional-unit.scala:547 assert (!(ma_ld && ma_st), \"Mutually-exclusive exceptions are firing.\")\n");	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:547:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:547:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:547:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign io_resp_valid = io_req_valid & (io_brupdate_b1_mispredict_mask & io_req_bits_uop_br_mask) == 8'h0;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:276:38, :482:7, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
  assign io_resp_bits_uop_ctrl_is_load = io_req_bits_uop_ctrl_is_load;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_ctrl_is_sta = io_req_bits_uop_ctrl_is_sta;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_ctrl_is_std = io_req_bits_uop_ctrl_is_std;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_br_mask = io_req_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, generators/boom/src/main/scala/v3/util/util.scala:85:{25,27}]
  assign io_resp_bits_uop_rob_idx = io_req_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_ldq_idx = io_req_bits_uop_ldq_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_stq_idx = io_req_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_pdst = io_req_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_mem_cmd = io_req_bits_uop_mem_cmd;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_mem_size = io_req_bits_uop_mem_size;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_mem_signed = io_req_bits_uop_mem_signed;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_is_fence = io_req_bits_uop_is_fence;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_is_amo = io_req_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_uses_ldq = io_req_bits_uop_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_uses_stq = io_req_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_uop_fp_val = io_req_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_data = io_req_bits_rs2_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7]
  assign io_resp_bits_addr = {_sum_T_3[38] ? (&(_sum_T_3[63:39])) : (|(_sum_T_3[63:39])), _sum_T_3[38:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, :493:42, :494:{20,24,43,58}, :495:58, :496:{30,43}]
  assign io_resp_bits_mxcpt_valid = ma_ld | ma_st;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, :530:{29,63}, :531:{29,104}, :538:26]
  assign io_resp_bits_sfence_valid = io_req_valid & io_req_bits_uop_mem_cmd == 5'h14;	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, :549:{45,72}]
  assign io_resp_bits_sfence_bits_rs1 = io_req_bits_uop_mem_size[0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, :550:59]
  assign io_resp_bits_sfence_bits_rs2 = io_req_bits_uop_mem_size[1];	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, :551:59]
  assign io_resp_bits_sfence_bits_addr = io_req_bits_rs1_data[38:0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/functional-unit.scala:482:7, :552:33]
endmodule

