// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RenameStage_1(	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
  input        clock,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
  input        reset,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
  output       io_ren_stalls_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren_stalls_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_kill,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_is_br,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_is_sfb,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [2:0] io_dec_uops_0_br_tag,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_ldst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_lrs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_lrs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_lrs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_0_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_0_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_0_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_frs3_en,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_1_is_br,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_1_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_1_is_sfb,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [2:0] io_dec_uops_1_br_tag,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_1_ldst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_1_lrs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_1_lrs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_1_lrs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_1_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_1_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_1_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_1_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_1_frs3_en,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_0_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_0_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_0_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_0_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_0_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_0_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_0_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_1_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_1_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_1_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_1_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_1_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_1_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_1_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [6:0] io_ren2_uops_1_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [2:0] io_brupdate_b2_uop_br_tag,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_brupdate_b2_mispredict,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dis_fire_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dis_fire_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dis_ready,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_wakeups_0_valid,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [6:0] io_wakeups_0_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_wakeups_0_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_wakeups_1_valid,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [6:0] io_wakeups_1_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_wakeups_1_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_com_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_com_valids_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [6:0] io_com_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [6:0] io_com_uops_0_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_com_uops_0_ldst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_com_uops_0_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_com_uops_0_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [6:0] io_com_uops_1_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [6:0] io_com_uops_1_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_com_uops_1_ldst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_com_uops_1_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_com_uops_1_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_rbk_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_rbk_valids_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_rollback,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_debug_rob_empty	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
);

  wire       _busytable_io_busy_resps_0_prs1_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  wire       _busytable_io_busy_resps_0_prs2_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  wire       _busytable_io_busy_resps_0_prs3_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  wire       _busytable_io_busy_resps_1_prs1_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  wire       _busytable_io_busy_resps_1_prs2_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  wire       _busytable_io_busy_resps_1_prs3_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  wire       _freelist_io_alloc_pregs_0_valid;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24]
  wire [5:0] _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24]
  wire       _freelist_io_alloc_pregs_1_valid;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24]
  wire [5:0] _freelist_io_alloc_pregs_1_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24]
  wire [5:0] _maptable_io_map_resps_0_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_0_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_0_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_1_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_1_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_1_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  wire [5:0] _maptable_io_map_resps_1_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  reg        r_uop_is_br;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_is_sfb;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [2:0] r_uop_br_tag;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [1:0] r_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [1:0] r_uop_lrs1_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [1:0] r_uop_lrs2_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_frs3_en;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_1_is_br;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_1_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_1_is_sfb;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [2:0] r_uop_1_br_tag;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_1_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_1_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_1_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [6:0] r_uop_1_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_1_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_1_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_1_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [5:0] r_uop_1_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_1_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [1:0] r_uop_1_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [1:0] r_uop_1_lrs1_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg  [1:0] r_uop_1_lrs2_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  reg        r_uop_1_frs3_en;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
  wire       _io_ren_stalls_0_T = r_uop_dst_rtype == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :248:78]
  wire       freelist_io_reqs_0 = r_uop_ldst_val & _io_ren_stalls_0_T & io_dis_fire_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :248:{52,78,88}]
  wire       ren2_br_tags_0_valid = io_dis_fire_0 & (r_uop_is_br & ~r_uop_is_sfb | r_uop_is_jalr);	// @[generators/boom/src/main/scala/v3/common/micro-op.scala:146:{33,36,45}, generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :249:43]
  wire       _rbk_valids_0_T = io_com_uops_0_dst_rtype == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:251:82]
  wire       rbk_valids_0 = io_com_uops_0_ldst_val & _rbk_valids_0_T & io_rbk_valids_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:251:82, :252:{54,92}]
  wire       _io_ren_stalls_1_T = r_uop_1_dst_rtype == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :248:78]
  wire       freelist_io_reqs_1 = r_uop_1_ldst_val & _io_ren_stalls_1_T & io_dis_fire_1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :248:{52,78,88}]
  wire       ren2_br_tags_1_valid = io_dis_fire_1 & (r_uop_1_is_br & ~r_uop_1_is_sfb | r_uop_1_is_jalr);	// @[generators/boom/src/main/scala/v3/common/micro-op.scala:146:{33,36,45}, generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :249:43]
  wire       _rbk_valids_1_T = io_com_uops_1_dst_rtype == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:251:82]
  wire       rbk_valids_1 = io_com_uops_1_ldst_val & _rbk_valids_1_T & io_rbk_valids_1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:251:82, :252:{54,92}]
  wire [6:0] bypassed_uop_pdst = {1'h0, _freelist_io_alloc_pregs_0_bits};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24, :314:14]
  wire [6:0] ren2_uops_1_pdst = {1'h0, _freelist_io_alloc_pregs_1_bits};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24, :314:14]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10]
      if (~reset & ~((|{~freelist_io_reqs_0, _freelist_io_alloc_pregs_0_bits}) & (|{~freelist_io_reqs_1, _freelist_io_alloc_pregs_1_bits}))) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24, :248:{52,88}, :308:{10,74,77,87,105}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10]
          $error("Assertion failed: [rename-stage] A uop is trying to allocate the zero physical register.\n    at rename-stage.scala:308 assert (ren2_alloc_reqs zip freelist.io.alloc_pregs map {case (r,p) => !r || p.bits =/= 0.U} reduce (_&&_),\n");	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10]
      end
      if (~reset & (io_wakeups_0_valid & io_wakeups_0_bits_uop_dst_rtype != 2'h1 | io_wakeups_1_valid & io_wakeups_1_bits_uop_dst_rtype != 2'h1)) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:308:10, :325:{10,41,65,84}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:325:10]
          $error("Assertion failed: [rename] Wakeup has wrong rtype.\n    at rename-stage.scala:325 assert (!(io.wakeups.map(x => x.valid && x.bits.uop.dst_rtype =/= rtype).reduce(_||_)),\n");	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:325:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:325:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:325:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire       bypassed_uop_bypass_sel_rs1_0 = freelist_io_reqs_0 & r_uop_ldst == r_uop_1_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :185:{77,87}, :248:{52,88}]
  wire       bypassed_uop_bypass_sel_rs2_0 = freelist_io_reqs_0 & r_uop_ldst == r_uop_1_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :186:{77,87}, :248:{52,88}]
  wire       bypassed_uop_bypass_sel_rs3_0 = freelist_io_reqs_0 & r_uop_ldst == r_uop_1_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :187:{77,87}, :248:{52,88}]
  wire       _GEN = io_kill | ~io_dis_ready;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
  wire [5:0] next_uop_ldst = _GEN ? r_uop_ldst : io_dec_uops_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire [5:0] next_uop_lrs1 = _GEN ? r_uop_lrs1 : io_dec_uops_0_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire [5:0] next_uop_lrs2 = _GEN ? r_uop_lrs2 : io_dec_uops_0_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire [5:0] next_uop_lrs3 = _GEN ? r_uop_lrs3 : io_dec_uops_0_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire       r_uop_bypass_hits_rs1_0 = freelist_io_reqs_0 & r_uop_ldst == next_uop_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :185:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs1_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :185:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs2_0 = freelist_io_reqs_0 & r_uop_ldst == next_uop_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :186:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs2_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :186:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs3_0 = freelist_io_reqs_0 & r_uop_ldst == next_uop_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :187:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs3_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :187:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_dst_0 = freelist_io_reqs_0 & r_uop_ldst == next_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :188:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_dst_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :188:{77,87}, :248:{52,88}]
  wire [5:0] next_uop_1_ldst = _GEN ? r_uop_1_ldst : io_dec_uops_1_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire [5:0] next_uop_1_lrs1 = _GEN ? r_uop_1_lrs1 : io_dec_uops_1_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire [5:0] next_uop_1_lrs2 = _GEN ? r_uop_1_lrs2 : io_dec_uops_1_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire [5:0] next_uop_1_lrs3 = _GEN ? r_uop_1_lrs3 : io_dec_uops_1_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30]
  wire       r_uop_bypass_hits_rs1_0_1 = freelist_io_reqs_0 & r_uop_ldst == next_uop_1_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :185:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs1_1_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_1_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :185:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs2_0_1 = freelist_io_reqs_0 & r_uop_ldst == next_uop_1_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :186:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs2_1_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_1_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :186:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs3_0_1 = freelist_io_reqs_0 & r_uop_ldst == next_uop_1_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :187:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_rs3_1_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_1_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :187:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_dst_0_1 = freelist_io_reqs_0 & r_uop_ldst == next_uop_1_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :188:{77,87}, :248:{52,88}]
  wire       r_uop_bypass_hits_dst_1_1 = freelist_io_reqs_1 & r_uop_1_ldst == next_uop_1_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :130:14, :132:20, :134:30, :188:{77,87}, :248:{52,88}]
  wire [1:0] r_uop_bypass_sel_rs1_enc = r_uop_bypass_hits_rs1_1 ? 2'h1 : {r_uop_bypass_hits_rs1_0, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:185:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_rs2_enc = r_uop_bypass_hits_rs2_1 ? 2'h1 : {r_uop_bypass_hits_rs2_0, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:186:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_rs3_enc = r_uop_bypass_hits_rs3_1 ? 2'h1 : {r_uop_bypass_hits_rs3_0, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:187:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_dst_enc = r_uop_bypass_hits_dst_1 ? 2'h1 : {r_uop_bypass_hits_dst_0, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:188:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_rs1_enc_1 = r_uop_bypass_hits_rs1_1_1 ? 2'h1 : {r_uop_bypass_hits_rs1_0_1, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:185:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_rs2_enc_1 = r_uop_bypass_hits_rs2_1_1 ? 2'h1 : {r_uop_bypass_hits_rs2_0_1, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:186:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_rs3_enc_1 = r_uop_bypass_hits_rs3_1_1 ? 2'h1 : {r_uop_bypass_hits_rs3_0_1, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:187:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [1:0] r_uop_bypass_sel_dst_enc_1 = r_uop_bypass_hits_dst_1_1 ? 2'h1 : {r_uop_bypass_hits_dst_0_1, 1'h0};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:188:77, src/main/scala/chisel3/util/Mux.scala:50:70]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
    if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_is_br <= io_dec_uops_0_is_br;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_is_jalr <= io_dec_uops_0_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_is_sfb <= io_dec_uops_0_is_sfb;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_br_tag <= io_dec_uops_0_br_tag;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    end
    if (r_uop_bypass_hits_rs1_0 | r_uop_bypass_hits_rs1_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:185:77, :195:49]
      r_uop_prs1 <= (r_uop_bypass_sel_rs1_enc[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_rs1_enc[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_prs1 <= {1'h0, _maptable_io_map_resps_0_prs1};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :287:20]
    if (r_uop_bypass_hits_rs2_0 | r_uop_bypass_hits_rs2_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:186:77, :196:49]
      r_uop_prs2 <= (r_uop_bypass_sel_rs2_enc[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_rs2_enc[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_prs2 <= {1'h0, _maptable_io_map_resps_0_prs2};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :288:20]
    if (r_uop_bypass_hits_rs3_0 | r_uop_bypass_hits_rs3_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:187:77, :197:49]
      r_uop_prs3 <= (r_uop_bypass_sel_rs3_enc[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_rs3_enc[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_prs3 <= {1'h0, _maptable_io_map_resps_0_prs3};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :289:20]
    if (r_uop_bypass_hits_dst_0 | r_uop_bypass_hits_dst_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:188:77, :198:49]
      r_uop_stale_pdst <= (r_uop_bypass_sel_dst_enc[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_dst_enc[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_stale_pdst <= {1'h0, _maptable_io_map_resps_0_stale_pdst};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :290:20]
    if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_ldst <= io_dec_uops_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_lrs1 <= io_dec_uops_0_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_lrs2 <= io_dec_uops_0_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_lrs3 <= io_dec_uops_0_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_ldst_val <= io_dec_uops_0_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_dst_rtype <= io_dec_uops_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_lrs1_rtype <= io_dec_uops_0_lrs1_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_lrs2_rtype <= io_dec_uops_0_lrs2_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_frs3_en <= io_dec_uops_0_frs3_en;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_is_br <= io_dec_uops_1_is_br;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_is_jalr <= io_dec_uops_1_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_is_sfb <= io_dec_uops_1_is_sfb;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_br_tag <= io_dec_uops_1_br_tag;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    end
    if (r_uop_bypass_hits_rs1_0_1 | r_uop_bypass_hits_rs1_1_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:185:77, :195:49]
      r_uop_1_prs1 <= (r_uop_bypass_sel_rs1_enc_1[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_rs1_enc_1[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_1_prs1 <= {1'h0, _maptable_io_map_resps_1_prs1};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :287:20]
    if (r_uop_bypass_hits_rs2_0_1 | r_uop_bypass_hits_rs2_1_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:186:77, :196:49]
      r_uop_1_prs2 <= (r_uop_bypass_sel_rs2_enc_1[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_rs2_enc_1[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_1_prs2 <= {1'h0, _maptable_io_map_resps_1_prs2};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :288:20]
    if (r_uop_bypass_hits_rs3_0_1 | r_uop_bypass_hits_rs3_1_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:187:77, :197:49]
      r_uop_1_prs3 <= (r_uop_bypass_sel_rs3_enc_1[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_rs3_enc_1[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_1_prs3 <= {1'h0, _maptable_io_map_resps_1_prs3};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :289:20]
    if (r_uop_bypass_hits_dst_0_1 | r_uop_bypass_hits_dst_1_1)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:188:77, :198:49]
      r_uop_1_stale_pdst <= (r_uop_bypass_sel_dst_enc_1[1] ? bypassed_uop_pdst : 7'h0) | (r_uop_bypass_sel_dst_enc_1[0] ? ren2_uops_1_pdst : 7'h0);	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :314:14, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_1_stale_pdst <= {1'h0, _maptable_io_map_resps_1_stale_pdst};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :222:24, :290:20]
    if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:130:14, :132:20, :134:30]
      r_uop_1_ldst <= io_dec_uops_1_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_lrs1 <= io_dec_uops_1_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_lrs2 <= io_dec_uops_1_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_lrs3 <= io_dec_uops_1_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_ldst_val <= io_dec_uops_1_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_dst_rtype <= io_dec_uops_1_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_lrs1_rtype <= io_dec_uops_1_lrs1_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_lrs2_rtype <= io_dec_uops_1_lrs2_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
      r_uop_1_frs3_en <= io_dec_uops_1_frs3_en;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:24];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
        for (logic [4:0] i = 5'h0; i < 5'h19; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
        end	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
        r_uop_is_br = _RANDOM[5'h4][26];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_is_jalr = _RANDOM[5'h4][27];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_is_sfb = _RANDOM[5'h4][29];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_br_tag = _RANDOM[5'h5][8:6];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_prs1 = _RANDOM[5'h7][19:13];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_prs2 = _RANDOM[5'h7][26:20];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_prs3 = {_RANDOM[5'h7][31:27], _RANDOM[5'h8][1:0]};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_stale_pdst = _RANDOM[5'h8][17:11];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_ldst = _RANDOM[5'hB][10:5];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_lrs1 = _RANDOM[5'hB][16:11];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_lrs2 = _RANDOM[5'hB][22:17];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_lrs3 = _RANDOM[5'hB][28:23];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_ldst_val = _RANDOM[5'hB][29];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_dst_rtype = _RANDOM[5'hB][31:30];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_lrs1_rtype = _RANDOM[5'hC][1:0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_lrs2_rtype = _RANDOM[5'hC][3:2];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_frs3_en = _RANDOM[5'hC][4];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_is_br = _RANDOM[5'h11][10];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_is_jalr = _RANDOM[5'h11][11];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_is_sfb = _RANDOM[5'h11][13];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_br_tag = _RANDOM[5'h11][24:22];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_prs1 = {_RANDOM[5'h13][31:29], _RANDOM[5'h14][3:0]};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_prs2 = _RANDOM[5'h14][10:4];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_prs3 = _RANDOM[5'h14][17:11];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_stale_pdst = {_RANDOM[5'h14][31:27], _RANDOM[5'h15][1:0]};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_ldst = _RANDOM[5'h17][26:21];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_lrs1 = {_RANDOM[5'h17][31:27], _RANDOM[5'h18][0]};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_lrs2 = _RANDOM[5'h18][6:1];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_lrs3 = _RANDOM[5'h18][12:7];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_ldst_val = _RANDOM[5'h18][13];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_dst_rtype = _RANDOM[5'h18][15:14];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_lrs1_rtype = _RANDOM[5'h18][17:16];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_lrs2_rtype = _RANDOM[5'h18][19:18];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
        r_uop_1_frs3_en = _RANDOM[5'h18][20];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RenameMapTable_1 maptable (	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
    .clock                     (clock),
    .reset                     (reset),
    .io_map_reqs_0_lrs1        (io_dec_uops_0_lrs1),
    .io_map_reqs_0_lrs2        (io_dec_uops_0_lrs2),
    .io_map_reqs_0_lrs3        (io_dec_uops_0_lrs3),
    .io_map_reqs_0_ldst        (io_dec_uops_0_ldst),
    .io_map_reqs_1_lrs1        (io_dec_uops_1_lrs1),
    .io_map_reqs_1_lrs2        (io_dec_uops_1_lrs2),
    .io_map_reqs_1_lrs3        (io_dec_uops_1_lrs3),
    .io_map_reqs_1_ldst        (io_dec_uops_1_ldst),
    .io_map_resps_0_prs1       (_maptable_io_map_resps_0_prs1),
    .io_map_resps_0_prs2       (_maptable_io_map_resps_0_prs2),
    .io_map_resps_0_prs3       (_maptable_io_map_resps_0_prs3),
    .io_map_resps_0_stale_pdst (_maptable_io_map_resps_0_stale_pdst),
    .io_map_resps_1_prs1       (_maptable_io_map_resps_1_prs1),
    .io_map_resps_1_prs2       (_maptable_io_map_resps_1_prs2),
    .io_map_resps_1_prs3       (_maptable_io_map_resps_1_prs3),
    .io_map_resps_1_stale_pdst (_maptable_io_map_resps_1_stale_pdst),
    .io_remap_reqs_0_ldst      (io_rollback ? io_com_uops_1_ldst : r_uop_ldst),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :270:30]
    .io_remap_reqs_0_pdst      (io_rollback ? io_com_uops_1_stale_pdst[5:0] : _freelist_io_alloc_pregs_0_bits),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14, :228:24, :271:30]
    .io_remap_reqs_0_valid     (freelist_io_reqs_0 | rbk_valids_1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:248:{52,88}, :252:{54,92}, :274:38]
    .io_remap_reqs_1_ldst      (io_rollback ? io_com_uops_0_ldst : r_uop_1_ldst),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :270:30]
    .io_remap_reqs_1_pdst      (io_rollback ? io_com_uops_0_stale_pdst[5:0] : _freelist_io_alloc_pregs_1_bits),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14, :228:24, :271:30]
    .io_remap_reqs_1_valid     (freelist_io_reqs_1 | rbk_valids_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:248:{52,88}, :252:{54,92}, :274:38]
    .io_ren_br_tags_0_valid    (ren2_br_tags_0_valid),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:249:43]
    .io_ren_br_tags_0_bits     (r_uop_br_tag),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_br_tags_1_valid    (ren2_br_tags_1_valid),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:249:43]
    .io_ren_br_tags_1_bits     (r_uop_1_br_tag),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_rollback               (io_rollback)
  );	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:222:24]
  RenameFreeList_1 freelist (	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24]
    .clock                     (clock),
    .reset                     (reset),
    .io_reqs_0                 (freelist_io_reqs_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:248:{52,88}]
    .io_reqs_1                 (freelist_io_reqs_1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:248:{52,88}]
    .io_alloc_pregs_0_valid    (_freelist_io_alloc_pregs_0_valid),
    .io_alloc_pregs_0_bits     (_freelist_io_alloc_pregs_0_bits),
    .io_alloc_pregs_1_valid    (_freelist_io_alloc_pregs_1_valid),
    .io_alloc_pregs_1_bits     (_freelist_io_alloc_pregs_1_bits),
    .io_dealloc_pregs_0_valid  (io_com_uops_0_ldst_val & _rbk_valids_0_T & io_com_valids_0 | rbk_valids_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:251:{54,82,92}, :252:{54,92}, :301:37]
    .io_dealloc_pregs_0_bits   (io_rollback ? io_com_uops_0_pdst[5:0] : io_com_uops_0_stale_pdst[5:0]),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14, :303:33]
    .io_dealloc_pregs_1_valid  (io_com_uops_1_ldst_val & _rbk_valids_1_T & io_com_valids_1 | rbk_valids_1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:251:{54,82,92}, :252:{54,92}, :301:37]
    .io_dealloc_pregs_1_bits   (io_rollback ? io_com_uops_1_pdst[5:0] : io_com_uops_1_stale_pdst[5:0]),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14, :303:33]
    .io_ren_br_tags_0_valid    (ren2_br_tags_0_valid),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:249:43]
    .io_ren_br_tags_0_bits     (r_uop_br_tag),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_br_tags_1_valid    (ren2_br_tags_1_valid),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:249:43]
    .io_ren_br_tags_1_bits     (r_uop_1_br_tag),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_debug_pipeline_empty   (io_debug_rob_empty)
  );	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:228:24]
  RenameBusyTable_1 busytable (	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
    .clock                     (clock),
    .reset                     (reset),
    .io_ren_uops_0_pdst        (bypassed_uop_pdst),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:314:14]
    .io_ren_uops_0_prs1        (r_uop_prs1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_uops_0_prs2        (r_uop_prs2),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_uops_0_prs3        (r_uop_prs3),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_uops_1_pdst        (ren2_uops_1_pdst),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:314:14]
    .io_ren_uops_1_prs1        (r_uop_1_prs1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_uops_1_prs2        (r_uop_1_prs2),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_ren_uops_1_prs3        (r_uop_1_prs3),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23]
    .io_busy_resps_0_prs1_busy (_busytable_io_busy_resps_0_prs1_busy),
    .io_busy_resps_0_prs2_busy (_busytable_io_busy_resps_0_prs2_busy),
    .io_busy_resps_0_prs3_busy (_busytable_io_busy_resps_0_prs3_busy),
    .io_busy_resps_1_prs1_busy (_busytable_io_busy_resps_1_prs1_busy),
    .io_busy_resps_1_prs2_busy (_busytable_io_busy_resps_1_prs2_busy),
    .io_busy_resps_1_prs3_busy (_busytable_io_busy_resps_1_prs3_busy),
    .io_rebusy_reqs_0          (freelist_io_reqs_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:248:{52,88}]
    .io_rebusy_reqs_1          (freelist_io_reqs_1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:248:{52,88}]
    .io_wb_pdsts_0             (io_wakeups_0_bits_uop_pdst[5:0]),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:323:25]
    .io_wb_pdsts_1             (io_wakeups_1_bits_uop_pdst[5:0]),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:323:25]
    .io_wb_valids_0            (io_wakeups_0_valid),
    .io_wb_valids_1            (io_wakeups_1_valid)
  );	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:232:25]
  assign io_ren_stalls_0 = _io_ren_stalls_0_T & ~_freelist_io_alloc_pregs_0_valid;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7, :228:24, :248:78, :347:{60,63}]
  assign io_ren_stalls_1 = _io_ren_stalls_1_T & ~_freelist_io_alloc_pregs_1_valid;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7, :228:24, :248:78, :347:{60,63}]
  assign io_ren2_uops_0_pdst = bypassed_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7, :314:14]
  assign io_ren2_uops_0_prs1 = r_uop_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
  assign io_ren2_uops_0_prs2 = r_uop_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
  assign io_ren2_uops_0_prs3 = r_uop_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
  assign io_ren2_uops_0_prs1_busy = r_uop_lrs1_rtype == 2'h1 & _busytable_io_busy_resps_0_prs1_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :232:25, :331:{37,47}]
  assign io_ren2_uops_0_prs2_busy = r_uop_lrs2_rtype == 2'h1 & _busytable_io_busy_resps_0_prs2_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :232:25, :332:{37,47}]
  assign io_ren2_uops_0_prs3_busy = r_uop_frs3_en & _busytable_io_busy_resps_0_prs3_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :232:25, :333:34]
  assign io_ren2_uops_0_stale_pdst = r_uop_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7]
  assign io_ren2_uops_1_pdst = ren2_uops_1_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:168:7, :314:14]
  assign io_ren2_uops_1_prs1 = bypassed_uop_bypass_sel_rs1_0 ? bypassed_uop_pdst : r_uop_1_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :183:18, :185:77, :202:{26,52}, :314:14]
  assign io_ren2_uops_1_prs2 = bypassed_uop_bypass_sel_rs2_0 ? bypassed_uop_pdst : r_uop_1_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :183:18, :186:77, :203:{26,52}, :314:14]
  assign io_ren2_uops_1_prs3 = bypassed_uop_bypass_sel_rs3_0 ? bypassed_uop_pdst : r_uop_1_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :183:18, :187:77, :204:{26,52}, :314:14]
  assign io_ren2_uops_1_prs1_busy = r_uop_1_lrs1_rtype == 2'h1 & _busytable_io_busy_resps_1_prs1_busy | bypassed_uop_bypass_sel_rs1_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :185:77, :207:45, :232:25, :331:{37,47}]
  assign io_ren2_uops_1_prs2_busy = r_uop_1_lrs2_rtype == 2'h1 & _busytable_io_busy_resps_1_prs2_busy | bypassed_uop_bypass_sel_rs2_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :186:77, :208:45, :232:25, :332:{37,47}]
  assign io_ren2_uops_1_prs3_busy = r_uop_1_frs3_en & _busytable_io_busy_resps_1_prs3_busy | bypassed_uop_bypass_sel_rs3_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :187:77, :209:45, :232:25, :333:34]
  assign io_ren2_uops_1_stale_pdst = freelist_io_reqs_0 & r_uop_ldst == r_uop_1_ldst ? bypassed_uop_pdst : r_uop_1_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:127:23, :168:7, :183:18, :188:{77,87}, :205:{26,52}, :248:{52,88}, :314:14]
endmodule

