// Generated by CIRCT firtool-1.75.0
module Atomics(	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:8:7]
  input         io_write,	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
  input  [2:0]  io_a_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
  input  [2:0]  io_a_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
  input  [7:0]  io_a_mask,	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
  input  [63:0] io_a_data,	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
  input  [63:0] io_data_in,	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
  output [63:0] io_data_out	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14]
);

  wire [63:0] _sum_T_18 = ({{8{io_a_mask[7]}}, {8{io_a_mask[6]}}, {8{io_a_mask[5]}}, {8{io_a_mask[4]}}, {8{io_a_mask[3]}}, {8{io_a_mask[2]}}, {8{io_a_mask[1]}}, {8{io_a_mask[0]}}} & io_a_data) + ({64{~(io_a_param[2])}} ^ io_data_in);	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:18:28, :23:18, :24:{29,44,57}]
  reg  [3:0]  casez_tmp;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8]
  always @(*) begin
    casez (io_a_param[1:0])	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:39:15]
      2'b00:
        casez_tmp = 4'h6;
      2'b01:
        casez_tmp = 4'hE;
      2'b10:
        casez_tmp = 4'h8;
      default:
        casez_tmp = 4'hC;
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:39:15]
  end // always @(*)
  reg  [1:0]  casez_tmp_0;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
  wire [7:0]  signBit = io_a_mask & {1'h1, ~(io_a_mask[7:1])};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:10:14, :22:{27,32,38}]
  wire [7:0]  _sign_a_T_65 = {io_a_data[63], io_a_data[55], io_a_data[47], io_a_data[39], io_a_data[31], io_a_data[23], io_a_data[15], io_a_data[7]} & signBit;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:22:27, :25:{33,36,83}]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
    casez (io_a_opcode)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      3'b000:
        casez_tmp_0 = 2'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      3'b001:
        casez_tmp_0 = 2'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      3'b010:
        casez_tmp_0 = io_a_param[2] ? 2'h2 : {1'h0, io_a_param[0] == ((|_sign_a_T_65) == (|({io_data_in[63], io_data_in[55], io_data_in[47], io_data_in[39], io_data_in[31], io_data_in[23], io_data_in[15], io_data_in[7]} & signBit)) ? ({_sum_T_18[63], _sum_T_18[55], _sum_T_18[47], _sum_T_18[39], _sum_T_18[31], _sum_T_18[23], _sum_T_18[15], _sum_T_18[7]} & signBit) == 8'h0 : io_a_param[1] == (|_sign_a_T_65))};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:18:28, :19:28, :20:28, :22:27, :24:57, :25:{33,36,83,94}, :29:32, :30:{21,29}, :31:25, :45:19, :48:8]
      3'b011:
        casez_tmp_0 = 2'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      3'b100:
        casez_tmp_0 = 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      3'b101:
        casez_tmp_0 = 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      3'b110:
        casez_tmp_0 = 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
      default:
        casez_tmp_0 = 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
  end // always @(*)
  wire [1:0]  select = io_write ? 2'h1 : casez_tmp_0;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:45:19]
  reg  [7:0]  casez_tmp_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_174 = casez_tmp >> {2'h0, io_a_data[15], io_data_in[15]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_171 = casez_tmp >> {2'h0, io_a_data[14], io_data_in[14]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_168 = casez_tmp >> {2'h0, io_a_data[13], io_data_in[13]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_165 = casez_tmp >> {2'h0, io_a_data[12], io_data_in[12]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_162 = casez_tmp >> {2'h0, io_a_data[11], io_data_in[11]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_159 = casez_tmp >> {2'h0, io_a_data[10], io_data_in[10]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_156 = casez_tmp >> {2'h0, io_a_data[9], io_data_in[9]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_153 = casez_tmp >> {2'h0, io_a_data[8], io_data_in[8]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[1] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_1 = io_data_in[15:8];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_1 = io_a_data[15:8];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_1 = _sum_T_18[15:8];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_1 = {_logical_T_174[0], _logical_T_171[0], _logical_T_168[0], _logical_T_165[0], _logical_T_162[0], _logical_T_159[0], _logical_T_156[0], _logical_T_153[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_2;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_150 = casez_tmp >> {2'h0, io_a_data[7], io_data_in[7]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_147 = casez_tmp >> {2'h0, io_a_data[6], io_data_in[6]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_144 = casez_tmp >> {2'h0, io_a_data[5], io_data_in[5]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_141 = casez_tmp >> {2'h0, io_a_data[4], io_data_in[4]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_138 = casez_tmp >> {2'h0, io_a_data[3], io_data_in[3]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_135 = casez_tmp >> {2'h0, io_a_data[2], io_data_in[2]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_132 = casez_tmp >> {2'h0, io_a_data[1], io_data_in[1]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_129 = casez_tmp >> {2'h0, io_a_data[0], io_data_in[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[0] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_2 = io_data_in[7:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_2 = io_a_data[7:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_2 = _sum_T_18[7:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_2 = {_logical_T_150[0], _logical_T_147[0], _logical_T_144[0], _logical_T_141[0], _logical_T_138[0], _logical_T_135[0], _logical_T_132[0], _logical_T_129[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_3;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_222 = casez_tmp >> {2'h0, io_a_data[31], io_data_in[31]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_219 = casez_tmp >> {2'h0, io_a_data[30], io_data_in[30]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_216 = casez_tmp >> {2'h0, io_a_data[29], io_data_in[29]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_213 = casez_tmp >> {2'h0, io_a_data[28], io_data_in[28]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_210 = casez_tmp >> {2'h0, io_a_data[27], io_data_in[27]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_207 = casez_tmp >> {2'h0, io_a_data[26], io_data_in[26]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_204 = casez_tmp >> {2'h0, io_a_data[25], io_data_in[25]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_201 = casez_tmp >> {2'h0, io_a_data[24], io_data_in[24]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[3] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_3 = io_data_in[31:24];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_3 = io_a_data[31:24];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_3 = _sum_T_18[31:24];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_3 = {_logical_T_222[0], _logical_T_219[0], _logical_T_216[0], _logical_T_213[0], _logical_T_210[0], _logical_T_207[0], _logical_T_204[0], _logical_T_201[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_4;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_198 = casez_tmp >> {2'h0, io_a_data[23], io_data_in[23]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_195 = casez_tmp >> {2'h0, io_a_data[22], io_data_in[22]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_192 = casez_tmp >> {2'h0, io_a_data[21], io_data_in[21]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_189 = casez_tmp >> {2'h0, io_a_data[20], io_data_in[20]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_186 = casez_tmp >> {2'h0, io_a_data[19], io_data_in[19]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_183 = casez_tmp >> {2'h0, io_a_data[18], io_data_in[18]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_180 = casez_tmp >> {2'h0, io_a_data[17], io_data_in[17]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_177 = casez_tmp >> {2'h0, io_a_data[16], io_data_in[16]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[2] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_4 = io_data_in[23:16];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_4 = io_a_data[23:16];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_4 = _sum_T_18[23:16];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_4 = {_logical_T_198[0], _logical_T_195[0], _logical_T_192[0], _logical_T_189[0], _logical_T_186[0], _logical_T_183[0], _logical_T_180[0], _logical_T_177[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_5;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_270 = casez_tmp >> {2'h0, io_a_data[47], io_data_in[47]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_267 = casez_tmp >> {2'h0, io_a_data[46], io_data_in[46]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_264 = casez_tmp >> {2'h0, io_a_data[45], io_data_in[45]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_261 = casez_tmp >> {2'h0, io_a_data[44], io_data_in[44]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_258 = casez_tmp >> {2'h0, io_a_data[43], io_data_in[43]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_255 = casez_tmp >> {2'h0, io_a_data[42], io_data_in[42]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_252 = casez_tmp >> {2'h0, io_a_data[41], io_data_in[41]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_249 = casez_tmp >> {2'h0, io_a_data[40], io_data_in[40]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[5] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_5 = io_data_in[47:40];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_5 = io_a_data[47:40];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_5 = _sum_T_18[47:40];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_5 = {_logical_T_270[0], _logical_T_267[0], _logical_T_264[0], _logical_T_261[0], _logical_T_258[0], _logical_T_255[0], _logical_T_252[0], _logical_T_249[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_6;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_246 = casez_tmp >> {2'h0, io_a_data[39], io_data_in[39]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_243 = casez_tmp >> {2'h0, io_a_data[38], io_data_in[38]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_240 = casez_tmp >> {2'h0, io_a_data[37], io_data_in[37]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_237 = casez_tmp >> {2'h0, io_a_data[36], io_data_in[36]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_234 = casez_tmp >> {2'h0, io_a_data[35], io_data_in[35]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_231 = casez_tmp >> {2'h0, io_a_data[34], io_data_in[34]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_228 = casez_tmp >> {2'h0, io_a_data[33], io_data_in[33]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_225 = casez_tmp >> {2'h0, io_a_data[32], io_data_in[32]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[4] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_6 = io_data_in[39:32];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_6 = io_a_data[39:32];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_6 = _sum_T_18[39:32];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_6 = {_logical_T_246[0], _logical_T_243[0], _logical_T_240[0], _logical_T_237[0], _logical_T_234[0], _logical_T_231[0], _logical_T_228[0], _logical_T_225[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_7;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_318 = casez_tmp >> {2'h0, io_a_data[63], io_data_in[63]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_315 = casez_tmp >> {2'h0, io_a_data[62], io_data_in[62]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_312 = casez_tmp >> {2'h0, io_a_data[61], io_data_in[61]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_309 = casez_tmp >> {2'h0, io_a_data[60], io_data_in[60]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_306 = casez_tmp >> {2'h0, io_a_data[59], io_data_in[59]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_303 = casez_tmp >> {2'h0, io_a_data[58], io_data_in[58]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_300 = casez_tmp >> {2'h0, io_a_data[57], io_data_in[57]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_297 = casez_tmp >> {2'h0, io_a_data[56], io_data_in[56]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[7] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_7 = io_data_in[63:56];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_7 = io_a_data[63:56];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_7 = _sum_T_18[63:56];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_7 = {_logical_T_318[0], _logical_T_315[0], _logical_T_312[0], _logical_T_309[0], _logical_T_306[0], _logical_T_303[0], _logical_T_300[0], _logical_T_297[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  reg  [7:0]  casez_tmp_8;	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
  wire [3:0]  _logical_T_294 = casez_tmp >> {2'h0, io_a_data[55], io_data_in[55]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_291 = casez_tmp >> {2'h0, io_a_data[54], io_data_in[54]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_288 = casez_tmp >> {2'h0, io_a_data[53], io_data_in[53]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_285 = casez_tmp >> {2'h0, io_a_data[52], io_data_in[52]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_282 = casez_tmp >> {2'h0, io_a_data[51], io_data_in[51]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_279 = casez_tmp >> {2'h0, io_a_data[50], io_data_in[50]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_276 = casez_tmp >> {2'h0, io_a_data[49], io_data_in[49]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  wire [3:0]  _logical_T_273 = casez_tmp >> {2'h0, io_a_data[48], io_data_in[48]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:25:36, :41:8]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21]
    casez (io_a_mask[6] ? select : 2'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
      2'b00:
        casez_tmp_8 = io_data_in[55:48];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b01:
        casez_tmp_8 = io_a_data[55:48];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:58:21, :59:59]
      2'b10:
        casez_tmp_8 = _sum_T_18[55:48];	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:57, :58:21, :59:59]
      default:
        casez_tmp_8 = {_logical_T_294[0], _logical_T_291[0], _logical_T_288[0], _logical_T_285[0], _logical_T_282[0], _logical_T_279[0], _logical_T_276[0], _logical_T_273[0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:41:8, :58:21, :59:59]
    endcase	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:24:29, :45:19, :57:47, :58:21]
  end // always @(*)
  assign io_data_out = {casez_tmp_7, casez_tmp_8, casez_tmp_5, casez_tmp_6, casez_tmp_3, casez_tmp_4, casez_tmp_1, casez_tmp_2};	// @[generators/rocket-chip/src/main/scala/tilelink/Atomics.scala:8:7, :58:21]
endmodule

