// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomPipelinedMultiplier(	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
  input  [4:0]  io_req_bits_fn,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
  input         io_req_bits_dw,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
  input  [63:0] io_req_bits_in1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
  input  [63:0] io_req_bits_in2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
  output [63:0] io_resp_bits_data	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
);

  reg         in_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [4:0]  in_pipe_b_fn;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         in_pipe_b_dw;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [63:0] in_pipe_b_in1;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [63:0] in_pipe_b_in2;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         s1_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:86:27]
  reg  [63:0] s1_p00;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:87:29]
  reg  [63:0] s1_p10;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:88:29]
  reg  [63:0] s1_p01;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:89:29]
  reg  [63:0] s1_p11;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:90:29]
  reg         s1_cmdHi;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:91:29]
  reg         s1_cmdHalf;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:92:29]
  reg  [63:0] out_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  wire [63:0] _GEN = {32'h0, in_pipe_b_in1[31:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:75:23, :87:33, src/main/scala/chisel3/util/Valid.scala:142:26]
  wire [63:0] _GEN_0 = {32'h0, in_pipe_b_in2[31:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:77:23, :87:33, src/main/scala/chisel3/util/Valid.scala:142:26]
  wire [63:0] _GEN_1 = {32'h0, in_pipe_b_in1[63:32]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:74:23, :88:33, src/main/scala/chisel3/util/Valid.scala:142:26]
  wire [63:0] _GEN_2 = {32'h0, in_pipe_b_in2[63:32]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:76:23, :89:33, src/main/scala/chisel3/util/Valid.scala:142:26]
  wire [95:0] _hi_T_9 = {64'h0, s1_p00[63:32]} + {32'h0, s1_p10} + {32'h0, s1_p01} + {s1_p11, 32'h0};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:87:29, :88:29, :89:29, :90:29, :95:38, :96:11, :97:11, :98:11]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
      in_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s1_valid <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:86:27]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
      in_pipe_v <= io_req_valid;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s1_valid <= in_pipe_v;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:86:27, src/main/scala/chisel3/util/Valid.scala:141:24]
    end
    if (io_req_valid) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:56:14]
      in_pipe_b_fn <= io_req_bits_fn;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      in_pipe_b_dw <= io_req_bits_dw;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      in_pipe_b_in1 <= io_req_bits_in1;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      in_pipe_b_in2 <= io_req_bits_in2;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (in_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      s1_p00 <= _GEN * _GEN_0;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:87:{29,33}]
      s1_p10 <= _GEN_1 * _GEN_0;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:87:33, :88:{29,33}]
      s1_p01 <= _GEN * _GEN_2;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:87:33, :89:{29,33}]
      s1_p11 <= _GEN_1 * _GEN_2 - ((~(in_pipe_b_fn[1] & in_pipe_b_fn[0]) & in_pipe_b_in1[63] ? in_pipe_b_in2 : 64'h0) + (~(in_pipe_b_fn[1]) & in_pipe_b_in2[63] ? in_pipe_b_in1 : 64'h0));	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:69:{31,48}, :70:{19,35}, :71:19, :78:{22,36}, :79:{22,36}, :83:{17,49,54}, :88:33, :89:33, :90:{29,33,38}, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_cmdHi <= in_pipe_b_fn[0] | in_pipe_b_fn[1];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:69:{31,35,48}, :91:29, src/main/scala/chisel3/util/Valid.scala:142:26]
      s1_cmdHalf <= ~in_pipe_b_dw;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:72:48, :92:29, src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (s1_valid)	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:86:27]
      out_pipe_b <= s1_cmdHi ? _hi_T_9[95:32] : {s1_cmdHalf ? {32{s1_p00[31]}} : _hi_T_9[31:0], s1_p00[31:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:87:29, :91:29, :92:29, :96:11, :97:11, :98:11, :99:28, :101:{18,35}, :102:{18,34,48}, :103:35, src/main/scala/chisel3/util/Valid.scala:142:26]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:14];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
        end	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
        in_pipe_v = _RANDOM[4'h0][0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, src/main/scala/chisel3/util/Valid.scala:141:24]
        in_pipe_b_fn = _RANDOM[4'h0][5:1];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        in_pipe_b_dw = _RANDOM[4'h0][6];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        in_pipe_b_in1 = {_RANDOM[4'h0][31:7], _RANDOM[4'h1], _RANDOM[4'h2][6:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26]
        in_pipe_b_in2 = {_RANDOM[4'h2][31:7], _RANDOM[4'h3], _RANDOM[4'h4][6:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_valid = _RANDOM[4'h4][12];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :86:27, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_p00 = {_RANDOM[4'h4][31:13], _RANDOM[4'h5], _RANDOM[4'h6][12:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :87:29, src/main/scala/chisel3/util/Valid.scala:142:26]
        s1_p10 = {_RANDOM[4'h6][31:13], _RANDOM[4'h7], _RANDOM[4'h8][12:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :87:29, :88:29]
        s1_p01 = {_RANDOM[4'h8][31:13], _RANDOM[4'h9], _RANDOM[4'hA][12:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :88:29, :89:29]
        s1_p11 = {_RANDOM[4'hA][31:13], _RANDOM[4'hB], _RANDOM[4'hC][12:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :89:29, :90:29]
        s1_cmdHi = _RANDOM[4'hC][13];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :90:29, :91:29]
        s1_cmdHalf = _RANDOM[4'hC][14];	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :90:29, :92:29]
        out_pipe_b = {_RANDOM[4'hC][31:16], _RANDOM[4'hD], _RANDOM[4'hE][15:0]};	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, :90:29, src/main/scala/chisel3/util/Valid.scala:142:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_resp_bits_data = out_pipe_b;	// @[generators/boom/src/main/scala/v3/exu/execution-units/pipelined-mul.scala:51:7, src/main/scala/chisel3/util/Valid.scala:142:26]
endmodule

