// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RegisterFileSynthesizable_1(	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
  input  [6:0]  io_read_ports_0_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  output [63:0] io_read_ports_0_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_read_ports_1_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  output [63:0] io_read_ports_1_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_read_ports_2_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  output [63:0] io_read_ports_2_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_read_ports_3_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  output [63:0] io_read_ports_3_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_read_ports_4_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  output [63:0] io_read_ports_4_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_read_ports_5_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  output [63:0] io_read_ports_5_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input         io_write_ports_0_valid,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_write_ports_0_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [63:0] io_write_ports_0_bits_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input         io_write_ports_1_valid,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_write_ports_1_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [63:0] io_write_ports_1_bits_data,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input         io_write_ports_2_valid,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [6:0]  io_write_ports_2_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
  input  [63:0] io_write_ports_2_bits_data	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:82:14]
);

  wire [63:0] _regfile_ext_R0_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  wire [63:0] _regfile_ext_R1_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  wire [63:0] _regfile_ext_R2_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  wire [63:0] _regfile_ext_R3_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  wire [63:0] _regfile_ext_R4_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  wire [63:0] _regfile_ext_R5_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  reg         write_ports_0_valid_REG;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42]
  reg  [6:0]  write_ports_0_bits_addr_REG;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:145:42]
  reg  [63:0] write_ports_0_bits_data_REG;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:146:42]
  reg  [6:0]  read_addrs_0;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  reg  [6:0]  read_addrs_1;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  reg  [6:0]  read_addrs_2;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  reg  [6:0]  read_addrs_3;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  reg  [6:0]  read_addrs_4;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  reg  [6:0]  read_addrs_5;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  wire        bypass_ens_0 = write_ports_0_valid_REG & write_ports_0_bits_addr_REG == read_addrs_0;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :158:50, :178:59, :179:21]
  wire        bypass_ens_1 = io_write_ports_1_valid & io_write_ports_1_bits_addr == read_addrs_0;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_2 = io_write_ports_2_valid & io_write_ports_2_bits_addr == read_addrs_0;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_0_1 = write_ports_0_valid_REG & write_ports_0_bits_addr_REG == read_addrs_1;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :158:50, :178:59, :179:21]
  wire        bypass_ens_1_1 = io_write_ports_1_valid & io_write_ports_1_bits_addr == read_addrs_1;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_2_1 = io_write_ports_2_valid & io_write_ports_2_bits_addr == read_addrs_1;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_0_2 = write_ports_0_valid_REG & write_ports_0_bits_addr_REG == read_addrs_2;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :158:50, :178:59, :179:21]
  wire        bypass_ens_1_2 = io_write_ports_1_valid & io_write_ports_1_bits_addr == read_addrs_2;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_2_2 = io_write_ports_2_valid & io_write_ports_2_bits_addr == read_addrs_2;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_0_3 = write_ports_0_valid_REG & write_ports_0_bits_addr_REG == read_addrs_3;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :158:50, :178:59, :179:21]
  wire        bypass_ens_1_3 = io_write_ports_1_valid & io_write_ports_1_bits_addr == read_addrs_3;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_2_3 = io_write_ports_2_valid & io_write_ports_2_bits_addr == read_addrs_3;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_0_4 = write_ports_0_valid_REG & write_ports_0_bits_addr_REG == read_addrs_4;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :158:50, :178:59, :179:21]
  wire        bypass_ens_1_4 = io_write_ports_1_valid & io_write_ports_1_bits_addr == read_addrs_4;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_2_4 = io_write_ports_2_valid & io_write_ports_2_bits_addr == read_addrs_4;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_0_5 = write_ports_0_valid_REG & write_ports_0_bits_addr_REG == read_addrs_5;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :158:50, :178:59, :179:21]
  wire        bypass_ens_1_5 = io_write_ports_1_valid & io_write_ports_1_bits_addr == read_addrs_5;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  wire        bypass_ens_2_5 = io_write_ports_2_valid & io_write_ports_2_bits_addr == read_addrs_5;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50, :178:59, :179:21]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
    wire _GEN = write_ports_0_bits_addr_REG == 7'h0;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:145:42, :207:42]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
      if (~reset & ~(~write_ports_0_valid_REG | ~io_write_ports_1_valid | write_ports_0_bits_addr_REG != io_write_ports_1_bits_addr | _GEN)) begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :204:{15,16,38}, :205:{16,38}, :206:{42,72}, :207:42]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:204 assert(!write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
      end
      if (~reset & ~(~write_ports_0_valid_REG | ~io_write_ports_2_valid | write_ports_0_bits_addr_REG != io_write_ports_2_bits_addr | _GEN)) begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42, :145:42, :204:{15,16,38}, :205:{16,38}, :206:{42,72}, :207:42]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:204 assert(!write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
      end
      if (~reset & ~(~io_write_ports_1_valid | ~io_write_ports_2_valid | io_write_ports_1_bits_addr != io_write_ports_2_bits_addr | io_write_ports_1_bits_addr == 7'h0)) begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:{15,38}, :205:{16,38}, :206:{42,72}, :207:42]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:204 assert(!write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:204:15]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    if (reset)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
      write_ports_0_valid_REG <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42]
    else	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
      write_ports_0_valid_REG <= io_write_ports_0_valid;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42]
    write_ports_0_bits_addr_REG <= io_write_ports_0_bits_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:145:42]
    write_ports_0_bits_data_REG <= io_write_ports_0_bits_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:146:42]
    read_addrs_0 <= io_read_ports_0_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    read_addrs_1 <= io_read_ports_1_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    read_addrs_2 <= io_read_ports_2_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    read_addrs_3 <= io_read_ports_3_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    read_addrs_4 <= io_read_ports_4_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    read_addrs_5 <= io_read_ports_5_addr;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
        end	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
        write_ports_0_valid_REG = _RANDOM[2'h0][0];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :144:42]
        write_ports_0_bits_addr_REG = _RANDOM[2'h0][7:1];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :144:42, :145:42]
        write_ports_0_bits_data_REG = {_RANDOM[2'h0][31:8], _RANDOM[2'h1], _RANDOM[2'h2][7:0]};	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :144:42, :146:42]
        read_addrs_0 = _RANDOM[2'h2][14:8];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :146:42, :158:50]
        read_addrs_1 = _RANDOM[2'h2][21:15];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :146:42, :158:50]
        read_addrs_2 = _RANDOM[2'h2][28:22];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :146:42, :158:50]
        read_addrs_3 = {_RANDOM[2'h2][31:29], _RANDOM[2'h3][3:0]};	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :146:42, :158:50]
        read_addrs_4 = _RANDOM[2'h3][10:4];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :158:50]
        read_addrs_5 = _RANDOM[2'h3][17:11];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :158:50]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  regfile_80x64 regfile_ext (	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
    .R0_addr (read_addrs_5),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    .R0_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    .R0_clk  (clock),
    .R0_data (_regfile_ext_R0_data),
    .R1_addr (read_addrs_4),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    .R1_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    .R1_clk  (clock),
    .R1_data (_regfile_ext_R1_data),
    .R2_addr (read_addrs_3),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    .R2_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    .R2_clk  (clock),
    .R2_data (_regfile_ext_R2_data),
    .R3_addr (read_addrs_2),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    .R3_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    .R3_clk  (clock),
    .R3_data (_regfile_ext_R3_data),
    .R4_addr (read_addrs_1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    .R4_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    .R4_clk  (clock),
    .R4_data (_regfile_ext_R4_data),
    .R5_addr (read_addrs_0),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:158:50]
    .R5_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7]
    .R5_clk  (clock),
    .R5_data (_regfile_ext_R5_data),
    .W0_addr (io_write_ports_2_bits_addr),
    .W0_en   (io_write_ports_2_valid),
    .W0_clk  (clock),
    .W0_data (io_write_ports_2_bits_data),
    .W1_addr (io_write_ports_1_bits_addr),
    .W1_en   (io_write_ports_1_valid),
    .W1_clk  (clock),
    .W1_data (io_write_ports_1_bits_data),
    .W2_addr (write_ports_0_bits_addr_REG),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:145:42]
    .W2_en   (write_ports_0_valid_REG),	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:144:42]
    .W2_clk  (clock),
    .W2_data (write_ports_0_bits_data_REG)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:146:42]
  );	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:118:20]
  assign io_read_ports_0_data = bypass_ens_0 | bypass_ens_1 | bypass_ens_2 ? (bypass_ens_0 ? write_ports_0_bits_data_REG : 64'h0) | (bypass_ens_1 ? io_write_ports_1_bits_data : 64'h0) | (bypass_ens_2 ? io_write_ports_2_bits_data : 64'h0) : _regfile_ext_R5_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :118:20, :146:42, :178:59, :183:{35,55}, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_read_ports_1_data = bypass_ens_0_1 | bypass_ens_1_1 | bypass_ens_2_1 ? (bypass_ens_0_1 ? write_ports_0_bits_data_REG : 64'h0) | (bypass_ens_1_1 ? io_write_ports_1_bits_data : 64'h0) | (bypass_ens_2_1 ? io_write_ports_2_bits_data : 64'h0) : _regfile_ext_R4_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :118:20, :146:42, :178:59, :183:{35,55}, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_read_ports_2_data = bypass_ens_0_2 | bypass_ens_1_2 | bypass_ens_2_2 ? (bypass_ens_0_2 ? write_ports_0_bits_data_REG : 64'h0) | (bypass_ens_1_2 ? io_write_ports_1_bits_data : 64'h0) | (bypass_ens_2_2 ? io_write_ports_2_bits_data : 64'h0) : _regfile_ext_R3_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :118:20, :146:42, :178:59, :183:{35,55}, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_read_ports_3_data = bypass_ens_0_3 | bypass_ens_1_3 | bypass_ens_2_3 ? (bypass_ens_0_3 ? write_ports_0_bits_data_REG : 64'h0) | (bypass_ens_1_3 ? io_write_ports_1_bits_data : 64'h0) | (bypass_ens_2_3 ? io_write_ports_2_bits_data : 64'h0) : _regfile_ext_R2_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :118:20, :146:42, :178:59, :183:{35,55}, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_read_ports_4_data = bypass_ens_0_4 | bypass_ens_1_4 | bypass_ens_2_4 ? (bypass_ens_0_4 ? write_ports_0_bits_data_REG : 64'h0) | (bypass_ens_1_4 ? io_write_ports_1_bits_data : 64'h0) | (bypass_ens_2_4 ? io_write_ports_2_bits_data : 64'h0) : _regfile_ext_R1_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :118:20, :146:42, :178:59, :183:{35,55}, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_read_ports_5_data = bypass_ens_0_5 | bypass_ens_1_5 | bypass_ens_2_5 ? (bypass_ens_0_5 ? write_ports_0_bits_data_REG : 64'h0) | (bypass_ens_1_5 ? io_write_ports_1_bits_data : 64'h0) | (bypass_ens_2_5 ? io_write_ports_2_bits_data : 64'h0) : _regfile_ext_R0_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:106:7, :118:20, :146:42, :178:59, :183:{35,55}, src/main/scala/chisel3/util/Mux.scala:30:73]
endmodule

